package domain.logisticsManage;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PensionRepairExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public PensionRepairExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null || value.toString().equals("")) {
				addCriterion("1=1");
				return;
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null
					|| value1.toString().equals("")
					|| value2.toString().equals("")) {
				addCriterion("1=1");
				return;
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOlderIdIsNull() {
			addCriterion("older_id is null");
			return (Criteria) this;
		}

		public Criteria andOlderIdIsNotNull() {
			addCriterion("older_id is not null");
			return (Criteria) this;
		}

		public Criteria andOlderIdEqualTo(Long value) {
			addCriterion("older_id =", value, "olderId");
			return (Criteria) this;
		}

		public Criteria andOlderIdNotEqualTo(Long value) {
			addCriterion("older_id <>", value, "olderId");
			return (Criteria) this;
		}

		public Criteria andOlderIdGreaterThan(Long value) {
			addCriterion("older_id >", value, "olderId");
			return (Criteria) this;
		}

		public Criteria andOlderIdGreaterThanOrEqualTo(Long value) {
			addCriterion("older_id >=", value, "olderId");
			return (Criteria) this;
		}

		public Criteria andOlderIdLessThan(Long value) {
			addCriterion("older_id <", value, "olderId");
			return (Criteria) this;
		}

		public Criteria andOlderIdLessThanOrEqualTo(Long value) {
			addCriterion("older_id <=", value, "olderId");
			return (Criteria) this;
		}

		public Criteria andOlderIdIn(List<Long> values) {
			addCriterion("older_id in", values, "olderId");
			return (Criteria) this;
		}

		public Criteria andOlderIdNotIn(List<Long> values) {
			addCriterion("older_id not in", values, "olderId");
			return (Criteria) this;
		}

		public Criteria andOlderIdBetween(Long value1, Long value2) {
			addCriterion("older_id between", value1, value2, "olderId");
			return (Criteria) this;
		}

		public Criteria andOlderIdNotBetween(Long value1, Long value2) {
			addCriterion("older_id not between", value1, value2, "olderId");
			return (Criteria) this;
		}

		public Criteria andRoomIdIsNull() {
			addCriterion("room_id is null");
			return (Criteria) this;
		}

		public Criteria andRoomIdIsNotNull() {
			addCriterion("room_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoomIdEqualTo(Long value) {
			addCriterion("room_id =", value, "roomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdNotEqualTo(Long value) {
			addCriterion("room_id <>", value, "roomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdGreaterThan(Long value) {
			addCriterion("room_id >", value, "roomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdGreaterThanOrEqualTo(Long value) {
			addCriterion("room_id >=", value, "roomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdLessThan(Long value) {
			addCriterion("room_id <", value, "roomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdLessThanOrEqualTo(Long value) {
			addCriterion("room_id <=", value, "roomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdIn(List<Long> values) {
			addCriterion("room_id in", values, "roomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdNotIn(List<Long> values) {
			addCriterion("room_id not in", values, "roomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdBetween(Long value1, Long value2) {
			addCriterion("room_id between", value1, value2, "roomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdNotBetween(Long value1, Long value2) {
			addCriterion("room_id not between", value1, value2, "roomId");
			return (Criteria) this;
		}

		public Criteria andRepairDetailIsNull() {
			addCriterion("repair_detail is null");
			return (Criteria) this;
		}

		public Criteria andRepairDetailIsNotNull() {
			addCriterion("repair_detail is not null");
			return (Criteria) this;
		}

		public Criteria andRepairDetailEqualTo(String value) {
			addCriterion("repair_detail =", value, "repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailNotEqualTo(String value) {
			addCriterion("repair_detail <>", value, "repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailGreaterThan(String value) {
			addCriterion("repair_detail >", value, "repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailGreaterThanOrEqualTo(String value) {
			addCriterion("repair_detail >=", value, "repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailLessThan(String value) {
			addCriterion("repair_detail <", value, "repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailLessThanOrEqualTo(String value) {
			addCriterion("repair_detail <=", value, "repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailLike(String value) {
			addCriterion("repair_detail like", value, "repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailNotLike(String value) {
			addCriterion("repair_detail not like", value, "repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailIn(List<String> values) {
			addCriterion("repair_detail in", values, "repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailNotIn(List<String> values) {
			addCriterion("repair_detail not in", values, "repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailBetween(String value1, String value2) {
			addCriterion("repair_detail between", value1, value2,
					"repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairDetailNotBetween(String value1, String value2) {
			addCriterion("repair_detail not between", value1, value2,
					"repairDetail");
			return (Criteria) this;
		}

		public Criteria andRepairTypeIsNull() {
			addCriterion("repair_type is null");
			return (Criteria) this;
		}

		public Criteria andRepairTypeIsNotNull() {
			addCriterion("repair_type is not null");
			return (Criteria) this;
		}

		public Criteria andRepairTypeEqualTo(Integer value) {
			addCriterion("repair_type =", value, "repairType");
			return (Criteria) this;
		}

		public Criteria andRepairTypeNotEqualTo(Integer value) {
			addCriterion("repair_type <>", value, "repairType");
			return (Criteria) this;
		}

		public Criteria andRepairTypeGreaterThan(Integer value) {
			addCriterion("repair_type >", value, "repairType");
			return (Criteria) this;
		}

		public Criteria andRepairTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("repair_type >=", value, "repairType");
			return (Criteria) this;
		}

		public Criteria andRepairTypeLessThan(Integer value) {
			addCriterion("repair_type <", value, "repairType");
			return (Criteria) this;
		}

		public Criteria andRepairTypeLessThanOrEqualTo(Integer value) {
			addCriterion("repair_type <=", value, "repairType");
			return (Criteria) this;
		}

		public Criteria andRepairTypeIn(List<Integer> values) {
			addCriterion("repair_type in", values, "repairType");
			return (Criteria) this;
		}

		public Criteria andRepairTypeNotIn(List<Integer> values) {
			addCriterion("repair_type not in", values, "repairType");
			return (Criteria) this;
		}

		public Criteria andRepairTypeBetween(Integer value1, Integer value2) {
			addCriterion("repair_type between", value1, value2, "repairType");
			return (Criteria) this;
		}

		public Criteria andRepairTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("repair_type not between", value1, value2,
					"repairType");
			return (Criteria) this;
		}

		public Criteria andApplyTimeIsNull() {
			addCriterion("apply_time is null");
			return (Criteria) this;
		}

		public Criteria andApplyTimeIsNotNull() {
			addCriterion("apply_time is not null");
			return (Criteria) this;
		}

		public Criteria andApplyTimeEqualTo(Date value) {
			addCriterion("apply_time =", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeNotEqualTo(Date value) {
			addCriterion("apply_time <>", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeGreaterThan(Date value) {
			addCriterion("apply_time >", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("apply_time >=", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeLessThan(Date value) {
			addCriterion("apply_time <", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeLessThanOrEqualTo(Date value) {
			addCriterion("apply_time <=", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeIn(List<Date> values) {
			addCriterion("apply_time in", values, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeNotIn(List<Date> values) {
			addCriterion("apply_time not in", values, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeBetween(Date value1, Date value2) {
			addCriterion("apply_time between", value1, value2, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeNotBetween(Date value1, Date value2) {
			addCriterion("apply_time not between", value1, value2, "applyTime");
			return (Criteria) this;
		}

		public Criteria andRepairerIdIsNull() {
			addCriterion("repairer_id is null");
			return (Criteria) this;
		}

		public Criteria andRepairerIdIsNotNull() {
			addCriterion("repairer_id is not null");
			return (Criteria) this;
		}

		public Criteria andRepairerIdEqualTo(Long value) {
			addCriterion("repairer_id =", value, "repairerId");
			return (Criteria) this;
		}

		public Criteria andRepairerIdNotEqualTo(Long value) {
			addCriterion("repairer_id <>", value, "repairerId");
			return (Criteria) this;
		}

		public Criteria andRepairerIdGreaterThan(Long value) {
			addCriterion("repairer_id >", value, "repairerId");
			return (Criteria) this;
		}

		public Criteria andRepairerIdGreaterThanOrEqualTo(Long value) {
			addCriterion("repairer_id >=", value, "repairerId");
			return (Criteria) this;
		}

		public Criteria andRepairerIdLessThan(Long value) {
			addCriterion("repairer_id <", value, "repairerId");
			return (Criteria) this;
		}

		public Criteria andRepairerIdLessThanOrEqualTo(Long value) {
			addCriterion("repairer_id <=", value, "repairerId");
			return (Criteria) this;
		}

		public Criteria andRepairerIdIn(List<Long> values) {
			addCriterion("repairer_id in", values, "repairerId");
			return (Criteria) this;
		}

		public Criteria andRepairerIdNotIn(List<Long> values) {
			addCriterion("repairer_id not in", values, "repairerId");
			return (Criteria) this;
		}

		public Criteria andRepairerIdBetween(Long value1, Long value2) {
			addCriterion("repairer_id between", value1, value2, "repairerId");
			return (Criteria) this;
		}

		public Criteria andRepairerIdNotBetween(Long value1, Long value2) {
			addCriterion("repairer_id not between", value1, value2,
					"repairerId");
			return (Criteria) this;
		}

		public Criteria andSendFlagIsNull() {
			addCriterion("send_flag is null");
			return (Criteria) this;
		}

		public Criteria andSendFlagIsNotNull() {
			addCriterion("send_flag is not null");
			return (Criteria) this;
		}

		public Criteria andSendFlagEqualTo(Integer value) {
			addCriterion("send_flag =", value, "sendFlag");
			return (Criteria) this;
		}

		public Criteria andSendFlagNotEqualTo(Integer value) {
			addCriterion("send_flag <>", value, "sendFlag");
			return (Criteria) this;
		}

		public Criteria andSendFlagGreaterThan(Integer value) {
			addCriterion("send_flag >", value, "sendFlag");
			return (Criteria) this;
		}

		public Criteria andSendFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("send_flag >=", value, "sendFlag");
			return (Criteria) this;
		}

		public Criteria andSendFlagLessThan(Integer value) {
			addCriterion("send_flag <", value, "sendFlag");
			return (Criteria) this;
		}

		public Criteria andSendFlagLessThanOrEqualTo(Integer value) {
			addCriterion("send_flag <=", value, "sendFlag");
			return (Criteria) this;
		}

		public Criteria andSendFlagIn(List<Integer> values) {
			addCriterion("send_flag in", values, "sendFlag");
			return (Criteria) this;
		}

		public Criteria andSendFlagNotIn(List<Integer> values) {
			addCriterion("send_flag not in", values, "sendFlag");
			return (Criteria) this;
		}

		public Criteria andSendFlagBetween(Integer value1, Integer value2) {
			addCriterion("send_flag between", value1, value2, "sendFlag");
			return (Criteria) this;
		}

		public Criteria andSendFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("send_flag not between", value1, value2, "sendFlag");
			return (Criteria) this;
		}

		public Criteria andHandleFlagIsNull() {
			addCriterion("handle_flag is null");
			return (Criteria) this;
		}

		public Criteria andHandleFlagIsNotNull() {
			addCriterion("handle_flag is not null");
			return (Criteria) this;
		}

		public Criteria andHandleFlagEqualTo(Integer value) {
			addCriterion("handle_flag =", value, "handleFlag");
			return (Criteria) this;
		}

		public Criteria andHandleFlagNotEqualTo(Integer value) {
			addCriterion("handle_flag <>", value, "handleFlag");
			return (Criteria) this;
		}

		public Criteria andHandleFlagGreaterThan(Integer value) {
			addCriterion("handle_flag >", value, "handleFlag");
			return (Criteria) this;
		}

		public Criteria andHandleFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("handle_flag >=", value, "handleFlag");
			return (Criteria) this;
		}

		public Criteria andHandleFlagLessThan(Integer value) {
			addCriterion("handle_flag <", value, "handleFlag");
			return (Criteria) this;
		}

		public Criteria andHandleFlagLessThanOrEqualTo(Integer value) {
			addCriterion("handle_flag <=", value, "handleFlag");
			return (Criteria) this;
		}

		public Criteria andHandleFlagIn(List<Integer> values) {
			addCriterion("handle_flag in", values, "handleFlag");
			return (Criteria) this;
		}

		public Criteria andHandleFlagNotIn(List<Integer> values) {
			addCriterion("handle_flag not in", values, "handleFlag");
			return (Criteria) this;
		}

		public Criteria andHandleFlagBetween(Integer value1, Integer value2) {
			addCriterion("handle_flag between", value1, value2, "handleFlag");
			return (Criteria) this;
		}

		public Criteria andHandleFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("handle_flag not between", value1, value2,
					"handleFlag");
			return (Criteria) this;
		}

		public Criteria andPayFlagIsNull() {
			addCriterion("pay_flag is null");
			return (Criteria) this;
		}

		public Criteria andPayFlagIsNotNull() {
			addCriterion("pay_flag is not null");
			return (Criteria) this;
		}

		public Criteria andPayFlagEqualTo(Integer value) {
			addCriterion("pay_flag =", value, "payFlag");
			return (Criteria) this;
		}

		public Criteria andPayFlagNotEqualTo(Integer value) {
			addCriterion("pay_flag <>", value, "payFlag");
			return (Criteria) this;
		}

		public Criteria andPayFlagGreaterThan(Integer value) {
			addCriterion("pay_flag >", value, "payFlag");
			return (Criteria) this;
		}

		public Criteria andPayFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("pay_flag >=", value, "payFlag");
			return (Criteria) this;
		}

		public Criteria andPayFlagLessThan(Integer value) {
			addCriterion("pay_flag <", value, "payFlag");
			return (Criteria) this;
		}

		public Criteria andPayFlagLessThanOrEqualTo(Integer value) {
			addCriterion("pay_flag <=", value, "payFlag");
			return (Criteria) this;
		}

		public Criteria andPayFlagIn(List<Integer> values) {
			addCriterion("pay_flag in", values, "payFlag");
			return (Criteria) this;
		}

		public Criteria andPayFlagNotIn(List<Integer> values) {
			addCriterion("pay_flag not in", values, "payFlag");
			return (Criteria) this;
		}

		public Criteria andPayFlagBetween(Integer value1, Integer value2) {
			addCriterion("pay_flag between", value1, value2, "payFlag");
			return (Criteria) this;
		}

		public Criteria andPayFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("pay_flag not between", value1, value2, "payFlag");
			return (Criteria) this;
		}

		public Criteria andClearedIsNull() {
			addCriterion("cleared is null");
			return (Criteria) this;
		}

		public Criteria andClearedIsNotNull() {
			addCriterion("cleared is not null");
			return (Criteria) this;
		}

		public Criteria andClearedEqualTo(Integer value) {
			addCriterion("cleared =", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedNotEqualTo(Integer value) {
			addCriterion("cleared <>", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedGreaterThan(Integer value) {
			addCriterion("cleared >", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedGreaterThanOrEqualTo(Integer value) {
			addCriterion("cleared >=", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedLessThan(Integer value) {
			addCriterion("cleared <", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedLessThanOrEqualTo(Integer value) {
			addCriterion("cleared <=", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedIn(List<Integer> values) {
			addCriterion("cleared in", values, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedNotIn(List<Integer> values) {
			addCriterion("cleared not in", values, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedBetween(Integer value1, Integer value2) {
			addCriterion("cleared between", value1, value2, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedNotBetween(Integer value1, Integer value2) {
			addCriterion("cleared not between", value1, value2, "cleared");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("note is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("note is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("note =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("note <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("note >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("note >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("note <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("note <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("note like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("note not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("note in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("note not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("note between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("note not between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andManagerIdIsNull() {
			addCriterion("manager_id is null");
			return (Criteria) this;
		}

		public Criteria andManagerIdIsNotNull() {
			addCriterion("manager_id is not null");
			return (Criteria) this;
		}

		public Criteria andManagerIdEqualTo(Long value) {
			addCriterion("manager_id =", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotEqualTo(Long value) {
			addCriterion("manager_id <>", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdGreaterThan(Long value) {
			addCriterion("manager_id >", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdGreaterThanOrEqualTo(Long value) {
			addCriterion("manager_id >=", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdLessThan(Long value) {
			addCriterion("manager_id <", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdLessThanOrEqualTo(Long value) {
			addCriterion("manager_id <=", value, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdIn(List<Long> values) {
			addCriterion("manager_id in", values, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotIn(List<Long> values) {
			addCriterion("manager_id not in", values, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdBetween(Long value1, Long value2) {
			addCriterion("manager_id between", value1, value2, "managerId");
			return (Criteria) this;
		}

		public Criteria andManagerIdNotBetween(Long value1, Long value2) {
			addCriterion("manager_id not between", value1, value2, "managerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdIsNull() {
			addCriterion("payer_id is null");
			return (Criteria) this;
		}

		public Criteria andPayerIdIsNotNull() {
			addCriterion("payer_id is not null");
			return (Criteria) this;
		}

		public Criteria andPayerIdEqualTo(Long value) {
			addCriterion("payer_id =", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdNotEqualTo(Long value) {
			addCriterion("payer_id <>", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdGreaterThan(Long value) {
			addCriterion("payer_id >", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdGreaterThanOrEqualTo(Long value) {
			addCriterion("payer_id >=", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdLessThan(Long value) {
			addCriterion("payer_id <", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdLessThanOrEqualTo(Long value) {
			addCriterion("payer_id <=", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdIn(List<Long> values) {
			addCriterion("payer_id in", values, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdNotIn(List<Long> values) {
			addCriterion("payer_id not in", values, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdBetween(Long value1, Long value2) {
			addCriterion("payer_id between", value1, value2, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdNotBetween(Long value1, Long value2) {
			addCriterion("payer_id not between", value1, value2, "payerId");
			return (Criteria) this;
		}

		public Criteria andHandleTimeIsNull() {
			addCriterion("handle_time is null");
			return (Criteria) this;
		}

		public Criteria andHandleTimeIsNotNull() {
			addCriterion("handle_time is not null");
			return (Criteria) this;
		}

		public Criteria andHandleTimeEqualTo(Date value) {
			addCriterion("handle_time =", value, "handleTime");
			return (Criteria) this;
		}

		public Criteria andHandleTimeNotEqualTo(Date value) {
			addCriterion("handle_time <>", value, "handleTime");
			return (Criteria) this;
		}

		public Criteria andHandleTimeGreaterThan(Date value) {
			addCriterion("handle_time >", value, "handleTime");
			return (Criteria) this;
		}

		public Criteria andHandleTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("handle_time >=", value, "handleTime");
			return (Criteria) this;
		}

		public Criteria andHandleTimeLessThan(Date value) {
			addCriterion("handle_time <", value, "handleTime");
			return (Criteria) this;
		}

		public Criteria andHandleTimeLessThanOrEqualTo(Date value) {
			addCriterion("handle_time <=", value, "handleTime");
			return (Criteria) this;
		}

		public Criteria andHandleTimeIn(List<Date> values) {
			addCriterion("handle_time in", values, "handleTime");
			return (Criteria) this;
		}

		public Criteria andHandleTimeNotIn(List<Date> values) {
			addCriterion("handle_time not in", values, "handleTime");
			return (Criteria) this;
		}

		public Criteria andHandleTimeBetween(Date value1, Date value2) {
			addCriterion("handle_time between", value1, value2, "handleTime");
			return (Criteria) this;
		}

		public Criteria andHandleTimeNotBetween(Date value1, Date value2) {
			addCriterion("handle_time not between", value1, value2,
					"handleTime");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdIsNull() {
			addCriterion("ensure_emp_id is null");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdIsNotNull() {
			addCriterion("ensure_emp_id is not null");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdEqualTo(Long value) {
			addCriterion("ensure_emp_id =", value, "ensureEmpId");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdNotEqualTo(Long value) {
			addCriterion("ensure_emp_id <>", value, "ensureEmpId");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdGreaterThan(Long value) {
			addCriterion("ensure_emp_id >", value, "ensureEmpId");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ensure_emp_id >=", value, "ensureEmpId");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdLessThan(Long value) {
			addCriterion("ensure_emp_id <", value, "ensureEmpId");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdLessThanOrEqualTo(Long value) {
			addCriterion("ensure_emp_id <=", value, "ensureEmpId");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdIn(List<Long> values) {
			addCriterion("ensure_emp_id in", values, "ensureEmpId");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdNotIn(List<Long> values) {
			addCriterion("ensure_emp_id not in", values, "ensureEmpId");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdBetween(Long value1, Long value2) {
			addCriterion("ensure_emp_id between", value1, value2, "ensureEmpId");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpIdNotBetween(Long value1, Long value2) {
			addCriterion("ensure_emp_id not between", value1, value2,
					"ensureEmpId");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameIsNull() {
			addCriterion("ensure_emp_name is null");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameIsNotNull() {
			addCriterion("ensure_emp_name is not null");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameEqualTo(String value) {
			addCriterion("ensure_emp_name =", value, "ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameNotEqualTo(String value) {
			addCriterion("ensure_emp_name <>", value, "ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameGreaterThan(String value) {
			addCriterion("ensure_emp_name >", value, "ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameGreaterThanOrEqualTo(String value) {
			addCriterion("ensure_emp_name >=", value, "ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameLessThan(String value) {
			addCriterion("ensure_emp_name <", value, "ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameLessThanOrEqualTo(String value) {
			addCriterion("ensure_emp_name <=", value, "ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameLike(String value) {
			addCriterion("ensure_emp_name like", value, "ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameNotLike(String value) {
			addCriterion("ensure_emp_name not like", value, "ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameIn(List<String> values) {
			addCriterion("ensure_emp_name in", values, "ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameNotIn(List<String> values) {
			addCriterion("ensure_emp_name not in", values, "ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameBetween(String value1, String value2) {
			addCriterion("ensure_emp_name between", value1, value2,
					"ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureEmpNameNotBetween(String value1, String value2) {
			addCriterion("ensure_emp_name not between", value1, value2,
					"ensureEmpName");
			return (Criteria) this;
		}

		public Criteria andEnsureDateIsNull() {
			addCriterion("ensure_date is null");
			return (Criteria) this;
		}

		public Criteria andEnsureDateIsNotNull() {
			addCriterion("ensure_date is not null");
			return (Criteria) this;
		}

		public Criteria andEnsureDateEqualTo(Date value) {
			addCriterion("ensure_date =", value, "ensureDate");
			return (Criteria) this;
		}

		public Criteria andEnsureDateNotEqualTo(Date value) {
			addCriterion("ensure_date <>", value, "ensureDate");
			return (Criteria) this;
		}

		public Criteria andEnsureDateGreaterThan(Date value) {
			addCriterion("ensure_date >", value, "ensureDate");
			return (Criteria) this;
		}

		public Criteria andEnsureDateGreaterThanOrEqualTo(Date value) {
			addCriterion("ensure_date >=", value, "ensureDate");
			return (Criteria) this;
		}

		public Criteria andEnsureDateLessThan(Date value) {
			addCriterion("ensure_date <", value, "ensureDate");
			return (Criteria) this;
		}

		public Criteria andEnsureDateLessThanOrEqualTo(Date value) {
			addCriterion("ensure_date <=", value, "ensureDate");
			return (Criteria) this;
		}

		public Criteria andEnsureDateIn(List<Date> values) {
			addCriterion("ensure_date in", values, "ensureDate");
			return (Criteria) this;
		}

		public Criteria andEnsureDateNotIn(List<Date> values) {
			addCriterion("ensure_date not in", values, "ensureDate");
			return (Criteria) this;
		}

		public Criteria andEnsureDateBetween(Date value1, Date value2) {
			addCriterion("ensure_date between", value1, value2, "ensureDate");
			return (Criteria) this;
		}

		public Criteria andEnsureDateNotBetween(Date value1, Date value2) {
			addCriterion("ensure_date not between", value1, value2,
					"ensureDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pension_repair
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}