package domain.nurseManage;

import java.io.Serializable;
import java.util.Date;

public class PensionDaycare implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.nurse_id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private Long nurseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.nurse_type
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private Integer nurseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.older_id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private Long olderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.older_name
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private String olderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.nurse_time
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private Date nurseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.health_condition
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private String healthCondition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.nurse_medicine
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private String nurseMedicine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.nurser_id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private Long nurserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.nurser_name
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private String nurserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.execute_flag
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private Integer executeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.execute_time
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private Date executeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.evaluation
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private Integer evaluation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.cleared
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private Integer cleared;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_daycare.note
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_daycare
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.id
	 * @return  the value of pension_daycare.id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.id
	 * @param id  the value for pension_daycare.id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.nurse_id
	 * @return  the value of pension_daycare.nurse_id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public Long getNurseId() {
		return nurseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.nurse_id
	 * @param nurseId  the value for pension_daycare.nurse_id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setNurseId(Long nurseId) {
		this.nurseId = nurseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.nurse_type
	 * @return  the value of pension_daycare.nurse_type
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public Integer getNurseType() {
		return nurseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.nurse_type
	 * @param nurseType  the value for pension_daycare.nurse_type
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setNurseType(Integer nurseType) {
		this.nurseType = nurseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.older_id
	 * @return  the value of pension_daycare.older_id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public Long getOlderId() {
		return olderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.older_id
	 * @param olderId  the value for pension_daycare.older_id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setOlderId(Long olderId) {
		this.olderId = olderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.older_name
	 * @return  the value of pension_daycare.older_name
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public String getOlderName() {
		return olderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.older_name
	 * @param olderName  the value for pension_daycare.older_name
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setOlderName(String olderName) {
		this.olderName = olderName == null ? null : olderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.nurse_time
	 * @return  the value of pension_daycare.nurse_time
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public Date getNurseTime() {
		return nurseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.nurse_time
	 * @param nurseTime  the value for pension_daycare.nurse_time
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setNurseTime(Date nurseTime) {
		this.nurseTime = nurseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.health_condition
	 * @return  the value of pension_daycare.health_condition
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public String getHealthCondition() {
		return healthCondition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.health_condition
	 * @param healthCondition  the value for pension_daycare.health_condition
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setHealthCondition(String healthCondition) {
		this.healthCondition = healthCondition == null ? null : healthCondition
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.nurse_medicine
	 * @return  the value of pension_daycare.nurse_medicine
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public String getNurseMedicine() {
		return nurseMedicine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.nurse_medicine
	 * @param nurseMedicine  the value for pension_daycare.nurse_medicine
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setNurseMedicine(String nurseMedicine) {
		this.nurseMedicine = nurseMedicine == null ? null : nurseMedicine
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.nurser_id
	 * @return  the value of pension_daycare.nurser_id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public Long getNurserId() {
		return nurserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.nurser_id
	 * @param nurserId  the value for pension_daycare.nurser_id
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setNurserId(Long nurserId) {
		this.nurserId = nurserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.nurser_name
	 * @return  the value of pension_daycare.nurser_name
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public String getNurserName() {
		return nurserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.nurser_name
	 * @param nurserName  the value for pension_daycare.nurser_name
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setNurserName(String nurserName) {
		this.nurserName = nurserName == null ? null : nurserName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.execute_flag
	 * @return  the value of pension_daycare.execute_flag
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public Integer getExecuteFlag() {
		return executeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.execute_flag
	 * @param executeFlag  the value for pension_daycare.execute_flag
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setExecuteFlag(Integer executeFlag) {
		this.executeFlag = executeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.execute_time
	 * @return  the value of pension_daycare.execute_time
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public Date getExecuteTime() {
		return executeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.execute_time
	 * @param executeTime  the value for pension_daycare.execute_time
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setExecuteTime(Date executeTime) {
		this.executeTime = executeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.evaluation
	 * @return  the value of pension_daycare.evaluation
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public Integer getEvaluation() {
		return evaluation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.evaluation
	 * @param evaluation  the value for pension_daycare.evaluation
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setEvaluation(Integer evaluation) {
		this.evaluation = evaluation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.cleared
	 * @return  the value of pension_daycare.cleared
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public Integer getCleared() {
		return cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.cleared
	 * @param cleared  the value for pension_daycare.cleared
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setCleared(Integer cleared) {
		this.cleared = cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_daycare.note
	 * @return  the value of pension_daycare.note
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_daycare.note
	 * @param note  the value for pension_daycare.note
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_daycare
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PensionDaycare other = (PensionDaycare) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getNurseId() == null ? other.getNurseId() == null
						: this.getNurseId().equals(other.getNurseId()))
				&& (this.getNurseType() == null ? other.getNurseType() == null
						: this.getNurseType().equals(other.getNurseType()))
				&& (this.getOlderId() == null ? other.getOlderId() == null
						: this.getOlderId().equals(other.getOlderId()))
				&& (this.getOlderName() == null ? other.getOlderName() == null
						: this.getOlderName().equals(other.getOlderName()))
				&& (this.getNurseTime() == null ? other.getNurseTime() == null
						: this.getNurseTime().equals(other.getNurseTime()))
				&& (this.getHealthCondition() == null ? other
						.getHealthCondition() == null : this
						.getHealthCondition()
						.equals(other.getHealthCondition()))
				&& (this.getNurseMedicine() == null ? other.getNurseMedicine() == null
						: this.getNurseMedicine().equals(
								other.getNurseMedicine()))
				&& (this.getNurserId() == null ? other.getNurserId() == null
						: this.getNurserId().equals(other.getNurserId()))
				&& (this.getNurserName() == null ? other.getNurserName() == null
						: this.getNurserName().equals(other.getNurserName()))
				&& (this.getExecuteFlag() == null ? other.getExecuteFlag() == null
						: this.getExecuteFlag().equals(other.getExecuteFlag()))
				&& (this.getExecuteTime() == null ? other.getExecuteTime() == null
						: this.getExecuteTime().equals(other.getExecuteTime()))
				&& (this.getEvaluation() == null ? other.getEvaluation() == null
						: this.getEvaluation().equals(other.getEvaluation()))
				&& (this.getCleared() == null ? other.getCleared() == null
						: this.getCleared().equals(other.getCleared()))
				&& (this.getNote() == null ? other.getNote() == null : this
						.getNote().equals(other.getNote()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_daycare
	 * @mbggenerated  Thu Nov 21 08:49:30 CST 2013
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getNurseId() == null) ? 0 : getNurseId().hashCode());
		result = prime * result
				+ ((getNurseType() == null) ? 0 : getNurseType().hashCode());
		result = prime * result
				+ ((getOlderId() == null) ? 0 : getOlderId().hashCode());
		result = prime * result
				+ ((getOlderName() == null) ? 0 : getOlderName().hashCode());
		result = prime * result
				+ ((getNurseTime() == null) ? 0 : getNurseTime().hashCode());
		result = prime
				* result
				+ ((getHealthCondition() == null) ? 0 : getHealthCondition()
						.hashCode());
		result = prime
				* result
				+ ((getNurseMedicine() == null) ? 0 : getNurseMedicine()
						.hashCode());
		result = prime * result
				+ ((getNurserId() == null) ? 0 : getNurserId().hashCode());
		result = prime * result
				+ ((getNurserName() == null) ? 0 : getNurserName().hashCode());
		result = prime
				* result
				+ ((getExecuteFlag() == null) ? 0 : getExecuteFlag().hashCode());
		result = prime
				* result
				+ ((getExecuteTime() == null) ? 0 : getExecuteTime().hashCode());
		result = prime * result
				+ ((getEvaluation() == null) ? 0 : getEvaluation().hashCode());
		result = prime * result
				+ ((getCleared() == null) ? 0 : getCleared().hashCode());
		result = prime * result
				+ ((getNote() == null) ? 0 : getNote().hashCode());
		return result;
	}
}