package persistence.stockManage;

import domain.stockManage.PensionPurchaseEvaluate;
import domain.stockManage.PensionPurchaseEvaluateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.stockManage.PurchaseEvalDomain;

public interface PensionPurchaseEvaluateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int countByExample(PensionPurchaseEvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int deleteByExample(PensionPurchaseEvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int insert(PensionPurchaseEvaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int insertSelective(PensionPurchaseEvaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	List<PensionPurchaseEvaluate> selectByExample(
			PensionPurchaseEvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	PensionPurchaseEvaluate selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int updateByExampleSelective(
			@Param("record") PensionPurchaseEvaluate record,
			@Param("example") PensionPurchaseEvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int updateByExample(@Param("record") PensionPurchaseEvaluate record,
			@Param("example") PensionPurchaseEvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int updateByPrimaryKeySelective(PensionPurchaseEvaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_evaluate
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int updateByPrimaryKey(PensionPurchaseEvaluate record);

	/**
	 * 查询采购申请审核意见
	 * 
	 * @param applyId
	 * @return
	 */
	List<PurchaseEvalDomain> selectDeptEvalList(@Param("applyId") Long applyId);
}