package persistence.stockManage;

import domain.stockManage.PensionStorageinRecord;
import domain.stockManage.PensionStorageinRecordExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.stockManage.StorageInRecordDomain;

public interface PensionStorageinRecordMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	int countByExample(PensionStorageinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	int deleteByExample(PensionStorageinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	int insert(PensionStorageinRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	int insertSelective(PensionStorageinRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	List<PensionStorageinRecord> selectByExample(
			PensionStorageinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	PensionStorageinRecord selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	int updateByExampleSelective(
			@Param("record") PensionStorageinRecord record,
			@Param("example") PensionStorageinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	int updateByExample(@Param("record") PensionStorageinRecord record,
			@Param("example") PensionStorageinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionStorageinRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_storagein_record
	 * 
	 * @mbggenerated Tue Nov 26 16:10:30 CST 2013
	 */
	int updateByPrimaryKey(PensionStorageinRecord record);

	/**
	 * 查询入库记录
	 * 
	 * @param startDate
	 * @param endDate
	 * @return
	 */
	List<StorageInRecordDomain> selectStorageinRecord(
			@Param("startDate") Date startDate, @Param("endDate") Date endDate);
}