package persistence.stockManage;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import domain.stockManage.PensionPurchaseDetail;
import domain.stockManage.PensionPurchaseDetailExample;

public interface PensionPurchaseDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int countByExample(PensionPurchaseDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int deleteByExample(PensionPurchaseDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int insert(PensionPurchaseDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int insertSelective(PensionPurchaseDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	List<PensionPurchaseDetail> selectByExample(
			PensionPurchaseDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	PensionPurchaseDetail selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int updateByExampleSelective(@Param("record") PensionPurchaseDetail record,
			@Param("example") PensionPurchaseDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int updateByExample(@Param("record") PensionPurchaseDetail record,
			@Param("example") PensionPurchaseDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int updateByPrimaryKeySelective(PensionPurchaseDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_purchase_detail
	 * @mbggenerated  Mon Mar 10 13:47:34 CST 2014
	 */
	int updateByPrimaryKey(PensionPurchaseDetail record);

	/**
	 * 查询物资采购明细
	 * 
	 * @param recordId
	 * @return
	 */
	List<PensionPurchaseDetail> selectApplyDetail(
			@Param("recordId") Long recordId);

	/**
	 * 查询采购单生成物资采购明细
	 * 
	 * @return
	 */
	List<PensionPurchaseDetail> selectStorageoutDetail(@Param("startDate") Date startDate,
			@Param("endDate") Date endDate);
}