package domain.caterManage;

import java.io.Serializable;

public class PensionFoodIngredient implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_food_ingredient.id
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_food_ingredient.menu_id
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	private Long menuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_food_ingredient.NAME
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_food_ingredient.ingredient_qty
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	private Float ingredientQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_food_ingredient.qty_unit
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	private String qtyUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_food_ingredient.item_id
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	private Long itemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_food_ingredient.id
	 * @return  the value of pension_food_ingredient.id
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_food_ingredient.id
	 * @param id  the value for pension_food_ingredient.id
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_food_ingredient.menu_id
	 * @return  the value of pension_food_ingredient.menu_id
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public Long getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_food_ingredient.menu_id
	 * @param menuId  the value for pension_food_ingredient.menu_id
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_food_ingredient.NAME
	 * @return  the value of pension_food_ingredient.NAME
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_food_ingredient.NAME
	 * @param name  the value for pension_food_ingredient.NAME
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_food_ingredient.ingredient_qty
	 * @return  the value of pension_food_ingredient.ingredient_qty
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public Float getIngredientQty() {
		return ingredientQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_food_ingredient.ingredient_qty
	 * @param ingredientQty  the value for pension_food_ingredient.ingredient_qty
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public void setIngredientQty(Float ingredientQty) {
		this.ingredientQty = ingredientQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_food_ingredient.qty_unit
	 * @return  the value of pension_food_ingredient.qty_unit
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public String getQtyUnit() {
		return qtyUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_food_ingredient.qty_unit
	 * @param qtyUnit  the value for pension_food_ingredient.qty_unit
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public void setQtyUnit(String qtyUnit) {
		this.qtyUnit = qtyUnit == null ? null : qtyUnit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_food_ingredient.item_id
	 * @return  the value of pension_food_ingredient.item_id
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public Long getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_food_ingredient.item_id
	 * @param itemId  the value for pension_food_ingredient.item_id
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PensionFoodIngredient other = (PensionFoodIngredient) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getMenuId() == null ? other.getMenuId() == null : this
						.getMenuId().equals(other.getMenuId()))
				&& (this.getName() == null ? other.getName() == null : this
						.getName().equals(other.getName()))
				&& (this.getIngredientQty() == null ? other.getIngredientQty() == null
						: this.getIngredientQty().equals(
								other.getIngredientQty()))
				&& (this.getQtyUnit() == null ? other.getQtyUnit() == null
						: this.getQtyUnit().equals(other.getQtyUnit()))
				&& (this.getItemId() == null ? other.getItemId() == null : this
						.getItemId().equals(other.getItemId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getMenuId() == null) ? 0 : getMenuId().hashCode());
		result = prime * result
				+ ((getName() == null) ? 0 : getName().hashCode());
		result = prime
				* result
				+ ((getIngredientQty() == null) ? 0 : getIngredientQty()
						.hashCode());
		result = prime * result
				+ ((getQtyUnit() == null) ? 0 : getQtyUnit().hashCode());
		result = prime * result
				+ ((getItemId() == null) ? 0 : getItemId().hashCode());
		return result;
	}
}