package persistence.medicalManage;

import domain.medicalManage.PensionDosageOldername;
import domain.medicalManage.PensionDosageOldernameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionDosageOldernameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    int countByExample(PensionDosageOldernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    int deleteByExample(PensionDosageOldernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    int insert(PensionDosageOldername record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    int insertSelective(PensionDosageOldername record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    List<PensionDosageOldername> selectByExample(PensionDosageOldernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    PensionDosageOldername selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    int updateByExampleSelective(@Param("record") PensionDosageOldername record, @Param("example") PensionDosageOldernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    int updateByExample(@Param("record") PensionDosageOldername record, @Param("example") PensionDosageOldernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    int updateByPrimaryKeySelective(PensionDosageOldername record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dosage_oldername
     *
     * @mbggenerated Tue Oct 29 14:28:46 GMT+08:00 2013
     */
    int updateByPrimaryKey(PensionDosageOldername record);
}