package persistence.medicalManage;

import domain.medicalManage.PensionDrugreceiveDetail;
import domain.medicalManage.PensionDrugreceiveDetailExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.olderManage.DrugReceiveDetailDomain;

public interface PensionDrugreceiveDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	int countByExample(PensionDrugreceiveDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	int deleteByExample(PensionDrugreceiveDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	int insert(PensionDrugreceiveDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	int insertSelective(PensionDrugreceiveDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	List<PensionDrugreceiveDetail> selectByExample(
			PensionDrugreceiveDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	PensionDrugreceiveDetail selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	int updateByExampleSelective(
			@Param("record") PensionDrugreceiveDetail record,
			@Param("example") PensionDrugreceiveDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	int updateByExample(@Param("record") PensionDrugreceiveDetail record,
			@Param("example") PensionDrugreceiveDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	int updateByPrimaryKeySelective(PensionDrugreceiveDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_drugreceive_detail
	 * @mbggenerated  Tue Apr 15 16:04:57 CST 2014
	 */
	int updateByPrimaryKey(PensionDrugreceiveDetail record);

	/**
	 * 查询药物接收明细
	 * 
	 * @param recordId
	 * @return
	 */
	List<DrugReceiveDetailDomain> selectDrugDetails(
			@Param("recordId") Long recordId);

	/**
	 * 查询符合摆药条件的药物接收明细
	 * 
	 * @param drugId
	 * @param eatTime
	 * @return
	 */
	List<DrugReceiveDetailDomain> selecDrugDetailList(
			@Param("drugId") Long drugId, @Param("eatTime") Date eatTime,
			@Param("useFlag") int useFlag);
}