package domain.olderManage;

import java.io.Serializable;
import java.util.Date;

public class PensionNotbackontime implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_notbackontime.id
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_notbackontime.older_id
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	private Long olderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_notbackontime.leave_id
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	private Long leaveId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_notbackontime.reason
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_notbackontime.oldBackTime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	private Date oldbacktime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_notbackontime.newBackTime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	private Date newbacktime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_notbackontime.notes
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	private String notes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_notbackontime.cleared
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	private Integer cleared;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_notbackontime.id
	 * @return  the value of pension_notbackontime.id
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_notbackontime.id
	 * @param id  the value for pension_notbackontime.id
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_notbackontime.older_id
	 * @return  the value of pension_notbackontime.older_id
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public Long getOlderId() {
		return olderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_notbackontime.older_id
	 * @param olderId  the value for pension_notbackontime.older_id
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public void setOlderId(Long olderId) {
		this.olderId = olderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_notbackontime.leave_id
	 * @return  the value of pension_notbackontime.leave_id
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public Long getLeaveId() {
		return leaveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_notbackontime.leave_id
	 * @param leaveId  the value for pension_notbackontime.leave_id
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public void setLeaveId(Long leaveId) {
		this.leaveId = leaveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_notbackontime.reason
	 * @return  the value of pension_notbackontime.reason
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_notbackontime.reason
	 * @param reason  the value for pension_notbackontime.reason
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public void setReason(String reason) {
		this.reason = reason == null ? null : reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_notbackontime.oldBackTime
	 * @return  the value of pension_notbackontime.oldBackTime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public Date getOldbacktime() {
		return oldbacktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_notbackontime.oldBackTime
	 * @param oldbacktime  the value for pension_notbackontime.oldBackTime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public void setOldbacktime(Date oldbacktime) {
		this.oldbacktime = oldbacktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_notbackontime.newBackTime
	 * @return  the value of pension_notbackontime.newBackTime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public Date getNewbacktime() {
		return newbacktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_notbackontime.newBackTime
	 * @param newbacktime  the value for pension_notbackontime.newBackTime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public void setNewbacktime(Date newbacktime) {
		this.newbacktime = newbacktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_notbackontime.notes
	 * @return  the value of pension_notbackontime.notes
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_notbackontime.notes
	 * @param notes  the value for pension_notbackontime.notes
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public void setNotes(String notes) {
		this.notes = notes == null ? null : notes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_notbackontime.cleared
	 * @return  the value of pension_notbackontime.cleared
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public Integer getCleared() {
		return cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_notbackontime.cleared
	 * @param cleared  the value for pension_notbackontime.cleared
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	public void setCleared(Integer cleared) {
		this.cleared = cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PensionNotbackontime other = (PensionNotbackontime) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getOlderId() == null ? other.getOlderId() == null
						: this.getOlderId().equals(other.getOlderId()))
				&& (this.getLeaveId() == null ? other.getLeaveId() == null
						: this.getLeaveId().equals(other.getLeaveId()))
				&& (this.getReason() == null ? other.getReason() == null : this
						.getReason().equals(other.getReason()))
				&& (this.getOldbacktime() == null ? other.getOldbacktime() == null
						: this.getOldbacktime().equals(other.getOldbacktime()))
				&& (this.getNewbacktime() == null ? other.getNewbacktime() == null
						: this.getNewbacktime().equals(other.getNewbacktime()))
				&& (this.getNotes() == null ? other.getNotes() == null : this
						.getNotes().equals(other.getNotes()))
				&& (this.getCleared() == null ? other.getCleared() == null
						: this.getCleared().equals(other.getCleared()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getOlderId() == null) ? 0 : getOlderId().hashCode());
		result = prime * result
				+ ((getLeaveId() == null) ? 0 : getLeaveId().hashCode());
		result = prime * result
				+ ((getReason() == null) ? 0 : getReason().hashCode());
		result = prime
				* result
				+ ((getOldbacktime() == null) ? 0 : getOldbacktime().hashCode());
		result = prime
				* result
				+ ((getNewbacktime() == null) ? 0 : getNewbacktime().hashCode());
		result = prime * result
				+ ((getNotes() == null) ? 0 : getNotes().hashCode());
		result = prime * result
				+ ((getCleared() == null) ? 0 : getCleared().hashCode());
		return result;
	}
}