package domain.olderManage;

import java.io.Serializable;
import java.util.Date;

public class PensionDosagedetail implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.dosage_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Long dosageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.older_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private String olderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.older_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Long olderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.dept_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private String deptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.dept_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Long deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.instruction
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private String instruction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.eatTime
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Date eattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.period
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Integer period;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.isEatFood
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Integer iseatfood;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.drug_receive_detail_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Long drugReceiveDetailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.isCheck
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Integer ischeck;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.checkResult
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private String checkresult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.drug_receive_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Long drugReceiveId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.drug_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private String drugName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.single_dose
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Integer singleDose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.unit
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private String unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.checker_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Long checkerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.checker_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private String checkerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.isEnsure
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Integer isensure;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.ensure_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Long ensureId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.ensure_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private String ensureName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.notes
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private String notes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dosagedetail.cleared
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private Integer cleared;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_dosagedetail
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.id
	 * @return  the value of pension_dosagedetail.id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.id
	 * @param id  the value for pension_dosagedetail.id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.dosage_id
	 * @return  the value of pension_dosagedetail.dosage_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Long getDosageId() {
		return dosageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.dosage_id
	 * @param dosageId  the value for pension_dosagedetail.dosage_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setDosageId(Long dosageId) {
		this.dosageId = dosageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.older_name
	 * @return  the value of pension_dosagedetail.older_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public String getOlderName() {
		return olderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.older_name
	 * @param olderName  the value for pension_dosagedetail.older_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setOlderName(String olderName) {
		this.olderName = olderName == null ? null : olderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.older_id
	 * @return  the value of pension_dosagedetail.older_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Long getOlderId() {
		return olderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.older_id
	 * @param olderId  the value for pension_dosagedetail.older_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setOlderId(Long olderId) {
		this.olderId = olderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.dept_name
	 * @return  the value of pension_dosagedetail.dept_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.dept_name
	 * @param deptName  the value for pension_dosagedetail.dept_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName == null ? null : deptName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.dept_id
	 * @return  the value of pension_dosagedetail.dept_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Long getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.dept_id
	 * @param deptId  the value for pension_dosagedetail.dept_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.instruction
	 * @return  the value of pension_dosagedetail.instruction
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public String getInstruction() {
		return instruction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.instruction
	 * @param instruction  the value for pension_dosagedetail.instruction
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setInstruction(String instruction) {
		this.instruction = instruction == null ? null : instruction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.eatTime
	 * @return  the value of pension_dosagedetail.eatTime
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Date getEattime() {
		return eattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.eatTime
	 * @param eattime  the value for pension_dosagedetail.eatTime
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setEattime(Date eattime) {
		this.eattime = eattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.period
	 * @return  the value of pension_dosagedetail.period
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Integer getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.period
	 * @param period  the value for pension_dosagedetail.period
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setPeriod(Integer period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.isEatFood
	 * @return  the value of pension_dosagedetail.isEatFood
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Integer getIseatfood() {
		return iseatfood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.isEatFood
	 * @param iseatfood  the value for pension_dosagedetail.isEatFood
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setIseatfood(Integer iseatfood) {
		this.iseatfood = iseatfood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.drug_receive_detail_id
	 * @return  the value of pension_dosagedetail.drug_receive_detail_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Long getDrugReceiveDetailId() {
		return drugReceiveDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.drug_receive_detail_id
	 * @param drugReceiveDetailId  the value for pension_dosagedetail.drug_receive_detail_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setDrugReceiveDetailId(Long drugReceiveDetailId) {
		this.drugReceiveDetailId = drugReceiveDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.isCheck
	 * @return  the value of pension_dosagedetail.isCheck
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Integer getIscheck() {
		return ischeck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.isCheck
	 * @param ischeck  the value for pension_dosagedetail.isCheck
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setIscheck(Integer ischeck) {
		this.ischeck = ischeck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.checkResult
	 * @return  the value of pension_dosagedetail.checkResult
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public String getCheckresult() {
		return checkresult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.checkResult
	 * @param checkresult  the value for pension_dosagedetail.checkResult
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setCheckresult(String checkresult) {
		this.checkresult = checkresult == null ? null : checkresult.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.drug_receive_id
	 * @return  the value of pension_dosagedetail.drug_receive_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Long getDrugReceiveId() {
		return drugReceiveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.drug_receive_id
	 * @param drugReceiveId  the value for pension_dosagedetail.drug_receive_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setDrugReceiveId(Long drugReceiveId) {
		this.drugReceiveId = drugReceiveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.drug_name
	 * @return  the value of pension_dosagedetail.drug_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public String getDrugName() {
		return drugName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.drug_name
	 * @param drugName  the value for pension_dosagedetail.drug_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setDrugName(String drugName) {
		this.drugName = drugName == null ? null : drugName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.single_dose
	 * @return  the value of pension_dosagedetail.single_dose
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Integer getSingleDose() {
		return singleDose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.single_dose
	 * @param singleDose  the value for pension_dosagedetail.single_dose
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setSingleDose(Integer singleDose) {
		this.singleDose = singleDose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.unit
	 * @return  the value of pension_dosagedetail.unit
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.unit
	 * @param unit  the value for pension_dosagedetail.unit
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.checker_id
	 * @return  the value of pension_dosagedetail.checker_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Long getCheckerId() {
		return checkerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.checker_id
	 * @param checkerId  the value for pension_dosagedetail.checker_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setCheckerId(Long checkerId) {
		this.checkerId = checkerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.checker_name
	 * @return  the value of pension_dosagedetail.checker_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public String getCheckerName() {
		return checkerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.checker_name
	 * @param checkerName  the value for pension_dosagedetail.checker_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setCheckerName(String checkerName) {
		this.checkerName = checkerName == null ? null : checkerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.isEnsure
	 * @return  the value of pension_dosagedetail.isEnsure
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Integer getIsensure() {
		return isensure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.isEnsure
	 * @param isensure  the value for pension_dosagedetail.isEnsure
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setIsensure(Integer isensure) {
		this.isensure = isensure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.ensure_id
	 * @return  the value of pension_dosagedetail.ensure_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Long getEnsureId() {
		return ensureId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.ensure_id
	 * @param ensureId  the value for pension_dosagedetail.ensure_id
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setEnsureId(Long ensureId) {
		this.ensureId = ensureId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.ensure_name
	 * @return  the value of pension_dosagedetail.ensure_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public String getEnsureName() {
		return ensureName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.ensure_name
	 * @param ensureName  the value for pension_dosagedetail.ensure_name
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setEnsureName(String ensureName) {
		this.ensureName = ensureName == null ? null : ensureName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.notes
	 * @return  the value of pension_dosagedetail.notes
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.notes
	 * @param notes  the value for pension_dosagedetail.notes
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setNotes(String notes) {
		this.notes = notes == null ? null : notes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dosagedetail.cleared
	 * @return  the value of pension_dosagedetail.cleared
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public Integer getCleared() {
		return cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dosagedetail.cleared
	 * @param cleared  the value for pension_dosagedetail.cleared
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	public void setCleared(Integer cleared) {
		this.cleared = cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_dosagedetail
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PensionDosagedetail other = (PensionDosagedetail) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getDosageId() == null ? other.getDosageId() == null
						: this.getDosageId().equals(other.getDosageId()))
				&& (this.getOlderName() == null ? other.getOlderName() == null
						: this.getOlderName().equals(other.getOlderName()))
				&& (this.getOlderId() == null ? other.getOlderId() == null
						: this.getOlderId().equals(other.getOlderId()))
				&& (this.getDeptName() == null ? other.getDeptName() == null
						: this.getDeptName().equals(other.getDeptName()))
				&& (this.getDeptId() == null ? other.getDeptId() == null : this
						.getDeptId().equals(other.getDeptId()))
				&& (this.getInstruction() == null ? other.getInstruction() == null
						: this.getInstruction().equals(other.getInstruction()))
				&& (this.getEattime() == null ? other.getEattime() == null
						: this.getEattime().equals(other.getEattime()))
				&& (this.getPeriod() == null ? other.getPeriod() == null : this
						.getPeriod().equals(other.getPeriod()))
				&& (this.getIseatfood() == null ? other.getIseatfood() == null
						: this.getIseatfood().equals(other.getIseatfood()))
				&& (this.getDrugReceiveDetailId() == null ? other
						.getDrugReceiveDetailId() == null : this
						.getDrugReceiveDetailId().equals(
								other.getDrugReceiveDetailId()))
				&& (this.getIscheck() == null ? other.getIscheck() == null
						: this.getIscheck().equals(other.getIscheck()))
				&& (this.getCheckresult() == null ? other.getCheckresult() == null
						: this.getCheckresult().equals(other.getCheckresult()))
				&& (this.getDrugReceiveId() == null ? other.getDrugReceiveId() == null
						: this.getDrugReceiveId().equals(
								other.getDrugReceiveId()))
				&& (this.getDrugName() == null ? other.getDrugName() == null
						: this.getDrugName().equals(other.getDrugName()))
				&& (this.getSingleDose() == null ? other.getSingleDose() == null
						: this.getSingleDose().equals(other.getSingleDose()))
				&& (this.getUnit() == null ? other.getUnit() == null : this
						.getUnit().equals(other.getUnit()))
				&& (this.getCheckerId() == null ? other.getCheckerId() == null
						: this.getCheckerId().equals(other.getCheckerId()))
				&& (this.getCheckerName() == null ? other.getCheckerName() == null
						: this.getCheckerName().equals(other.getCheckerName()))
				&& (this.getIsensure() == null ? other.getIsensure() == null
						: this.getIsensure().equals(other.getIsensure()))
				&& (this.getEnsureId() == null ? other.getEnsureId() == null
						: this.getEnsureId().equals(other.getEnsureId()))
				&& (this.getEnsureName() == null ? other.getEnsureName() == null
						: this.getEnsureName().equals(other.getEnsureName()))
				&& (this.getNotes() == null ? other.getNotes() == null : this
						.getNotes().equals(other.getNotes()))
				&& (this.getCleared() == null ? other.getCleared() == null
						: this.getCleared().equals(other.getCleared()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_dosagedetail
	 * @mbggenerated  Fri Nov 22 10:33:26 CST 2013
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getDosageId() == null) ? 0 : getDosageId().hashCode());
		result = prime * result
				+ ((getOlderName() == null) ? 0 : getOlderName().hashCode());
		result = prime * result
				+ ((getOlderId() == null) ? 0 : getOlderId().hashCode());
		result = prime * result
				+ ((getDeptName() == null) ? 0 : getDeptName().hashCode());
		result = prime * result
				+ ((getDeptId() == null) ? 0 : getDeptId().hashCode());
		result = prime
				* result
				+ ((getInstruction() == null) ? 0 : getInstruction().hashCode());
		result = prime * result
				+ ((getEattime() == null) ? 0 : getEattime().hashCode());
		result = prime * result
				+ ((getPeriod() == null) ? 0 : getPeriod().hashCode());
		result = prime * result
				+ ((getIseatfood() == null) ? 0 : getIseatfood().hashCode());
		result = prime
				* result
				+ ((getDrugReceiveDetailId() == null) ? 0
						: getDrugReceiveDetailId().hashCode());
		result = prime * result
				+ ((getIscheck() == null) ? 0 : getIscheck().hashCode());
		result = prime
				* result
				+ ((getCheckresult() == null) ? 0 : getCheckresult().hashCode());
		result = prime
				* result
				+ ((getDrugReceiveId() == null) ? 0 : getDrugReceiveId()
						.hashCode());
		result = prime * result
				+ ((getDrugName() == null) ? 0 : getDrugName().hashCode());
		result = prime * result
				+ ((getSingleDose() == null) ? 0 : getSingleDose().hashCode());
		result = prime * result
				+ ((getUnit() == null) ? 0 : getUnit().hashCode());
		result = prime * result
				+ ((getCheckerId() == null) ? 0 : getCheckerId().hashCode());
		result = prime
				* result
				+ ((getCheckerName() == null) ? 0 : getCheckerName().hashCode());
		result = prime * result
				+ ((getIsensure() == null) ? 0 : getIsensure().hashCode());
		result = prime * result
				+ ((getEnsureId() == null) ? 0 : getEnsureId().hashCode());
		result = prime * result
				+ ((getEnsureName() == null) ? 0 : getEnsureName().hashCode());
		result = prime * result
				+ ((getNotes() == null) ? 0 : getNotes().hashCode());
		result = prime * result
				+ ((getCleared() == null) ? 0 : getCleared().hashCode());
		return result;
	}
	
	public void setCharterName(String charterName) {
		this.charterName = charterName;
	}

	public String getCharterName() {
		return charterName;
	}

	public void setDeliverName(String deliverName) {
		this.deliverName = deliverName;
	}

	public String getDeliverName() {
		return deliverName;
	}

	private String charterName;
	
	private String deliverName;
}