package domain.olderManage;

import java.io.Serializable;
import java.util.Date;

public class PensionOlderRecureMain implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_older_recure_main.id
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_older_recure_main.older_id
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private Long olderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_older_recure_main.recureItem_id
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private Long recureitemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_older_recure_main.startTime
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private Date starttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_older_recure_main.inputTime
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private Date inputtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_older_recure_main.inputer
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private Long inputer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_older_recure_main.isHandle
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private Integer ishandle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_older_recure_main.recureResult
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private String recureresult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_older_recure_main.notes
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private String notes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_older_recure_main.cleared
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private Integer cleared;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_older_recure_main
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_older_recure_main.id
	 * @return  the value of pension_older_recure_main.id
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_older_recure_main.id
	 * @param id  the value for pension_older_recure_main.id
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_older_recure_main.older_id
	 * @return  the value of pension_older_recure_main.older_id
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public Long getOlderId() {
		return olderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_older_recure_main.older_id
	 * @param olderId  the value for pension_older_recure_main.older_id
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public void setOlderId(Long olderId) {
		this.olderId = olderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_older_recure_main.recureItem_id
	 * @return  the value of pension_older_recure_main.recureItem_id
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public Long getRecureitemId() {
		return recureitemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_older_recure_main.recureItem_id
	 * @param recureitemId  the value for pension_older_recure_main.recureItem_id
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public void setRecureitemId(Long recureitemId) {
		this.recureitemId = recureitemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_older_recure_main.startTime
	 * @return  the value of pension_older_recure_main.startTime
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public Date getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_older_recure_main.startTime
	 * @param starttime  the value for pension_older_recure_main.startTime
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_older_recure_main.inputTime
	 * @return  the value of pension_older_recure_main.inputTime
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public Date getInputtime() {
		return inputtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_older_recure_main.inputTime
	 * @param inputtime  the value for pension_older_recure_main.inputTime
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public void setInputtime(Date inputtime) {
		this.inputtime = inputtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_older_recure_main.inputer
	 * @return  the value of pension_older_recure_main.inputer
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public Long getInputer() {
		return inputer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_older_recure_main.inputer
	 * @param inputer  the value for pension_older_recure_main.inputer
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public void setInputer(Long inputer) {
		this.inputer = inputer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_older_recure_main.isHandle
	 * @return  the value of pension_older_recure_main.isHandle
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public Integer getIshandle() {
		return ishandle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_older_recure_main.isHandle
	 * @param ishandle  the value for pension_older_recure_main.isHandle
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public void setIshandle(Integer ishandle) {
		this.ishandle = ishandle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_older_recure_main.recureResult
	 * @return  the value of pension_older_recure_main.recureResult
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public String getRecureresult() {
		return recureresult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_older_recure_main.recureResult
	 * @param recureresult  the value for pension_older_recure_main.recureResult
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public void setRecureresult(String recureresult) {
		this.recureresult = recureresult == null ? null : recureresult.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_older_recure_main.notes
	 * @return  the value of pension_older_recure_main.notes
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_older_recure_main.notes
	 * @param notes  the value for pension_older_recure_main.notes
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public void setNotes(String notes) {
		this.notes = notes == null ? null : notes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_older_recure_main.cleared
	 * @return  the value of pension_older_recure_main.cleared
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public Integer getCleared() {
		return cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_older_recure_main.cleared
	 * @param cleared  the value for pension_older_recure_main.cleared
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	public void setCleared(Integer cleared) {
		this.cleared = cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure_main
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PensionOlderRecureMain other = (PensionOlderRecureMain) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getOlderId() == null ? other.getOlderId() == null
						: this.getOlderId().equals(other.getOlderId()))
				&& (this.getRecureitemId() == null ? other.getRecureitemId() == null
						: this.getRecureitemId()
								.equals(other.getRecureitemId()))
				&& (this.getStarttime() == null ? other.getStarttime() == null
						: this.getStarttime().equals(other.getStarttime()))
				&& (this.getInputtime() == null ? other.getInputtime() == null
						: this.getInputtime().equals(other.getInputtime()))
				&& (this.getInputer() == null ? other.getInputer() == null
						: this.getInputer().equals(other.getInputer()))
				&& (this.getIshandle() == null ? other.getIshandle() == null
						: this.getIshandle().equals(other.getIshandle()))
				&& (this.getRecureresult() == null ? other.getRecureresult() == null
						: this.getRecureresult()
								.equals(other.getRecureresult()))
				&& (this.getNotes() == null ? other.getNotes() == null : this
						.getNotes().equals(other.getNotes()))
				&& (this.getCleared() == null ? other.getCleared() == null
						: this.getCleared().equals(other.getCleared()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure_main
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getOlderId() == null) ? 0 : getOlderId().hashCode());
		result = prime
				* result
				+ ((getRecureitemId() == null) ? 0 : getRecureitemId()
						.hashCode());
		result = prime * result
				+ ((getStarttime() == null) ? 0 : getStarttime().hashCode());
		result = prime * result
				+ ((getInputtime() == null) ? 0 : getInputtime().hashCode());
		result = prime * result
				+ ((getInputer() == null) ? 0 : getInputer().hashCode());
		result = prime * result
				+ ((getIshandle() == null) ? 0 : getIshandle().hashCode());
		result = prime
				* result
				+ ((getRecureresult() == null) ? 0 : getRecureresult()
						.hashCode());
		result = prime * result
				+ ((getNotes() == null) ? 0 : getNotes().hashCode());
		result = prime * result
				+ ((getCleared() == null) ? 0 : getCleared().hashCode());
		return result;
	}
}