package persistence.hrManage;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import domain.hrManage.PensionStaffArrange;
import domain.hrManage.PensionStaffArrangeExample;

public interface PensionStaffArrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    int countByExample(PensionStaffArrangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    int deleteByExample(PensionStaffArrangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    int insert(PensionStaffArrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    int insertSelective(PensionStaffArrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    List<PensionStaffArrange> selectByExample(PensionStaffArrangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    PensionStaffArrange selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    int updateByExampleSelective(@Param("record") PensionStaffArrange record, @Param("example") PensionStaffArrangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    int updateByExample(@Param("record") PensionStaffArrange record, @Param("example") PensionStaffArrangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    int updateByPrimaryKeySelective(PensionStaffArrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_staff_arrange
     *
     * @mbggenerated Tue Oct 29 15:53:41 GMT+08:00 2013
     */
    int updateByPrimaryKey(PensionStaffArrange record);
    
    List<PensionStaffArrange> selectStaffArranges(@Param("startDate")Date startDate,
    		@Param("endDate")Date endDate,
    		@Param("deptId")Long deptId, 
    		@Param("empId")Long empId);
}