package persistence.recoup;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import domain.recoup.RecoupApplyRecord;
import domain.recoup.RecoupApplyRecordExample;
import domain.recoup.RecoupApplyRecordExtend;

public interface RecoupApplyRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	int countByExample(RecoupApplyRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	int deleteByExample(RecoupApplyRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	int insert(RecoupApplyRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	int insertSelective(RecoupApplyRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	List<RecoupApplyRecord> selectByExample(RecoupApplyRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	RecoupApplyRecord selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	int updateByExampleSelective(@Param("record") RecoupApplyRecord record,
			@Param("example") RecoupApplyRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	int updateByExample(@Param("record") RecoupApplyRecord record,
			@Param("example") RecoupApplyRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	int updateByPrimaryKeySelective(RecoupApplyRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recoup_apply_record
	 * @mbggenerated  Sun Jul 06 21:50:40 CST 2014
	 */
	int updateByPrimaryKey(RecoupApplyRecord record);
	
	/**
	 * 
		* @Title: selectRecoupListBy 
		* @Description: TODO
		* @param @param projectCode
		* @param @param payState
		* @param @param applyDateStart
		* @param @param applyDateEnd
		* @param @return
		* @return List<RecoupApplyRecordExtend>
		* @throws 
		* @author Justin.Su
		* @date 2014-7-12 上午10:44:09
		* @version V1.0
	 */
	List<RecoupApplyRecordExtend> selectRecoupListBy(@Param("projectCode") String projectCode,@Param("payState") Integer payState,@Param("applyDateStart") Date applyDateStart,@Param("applyDateEnd") Date applyDateEnd);
}