package domain.financeManage;

import java.io.Serializable;
import java.util.Date;

public class PensionSettleRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_settle_record.id
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_settle_record.settler_id
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private Long settlerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_settle_record.settler_name
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private String settlerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_settle_record.change_time
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_settle_record.total_amount
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private Double totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_settle_record.income_amount
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private Float incomeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_settle_record.expenses_amount
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private Float expensesAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_settle_record.settletype_id
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private Long settletypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_settle_record.cleared
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private Integer cleared;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_settle_record.note
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pension_settle_record
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_settle_record.id
     *
     * @return the value of pension_settle_record.id
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_settle_record.id
     *
     * @param id the value for pension_settle_record.id
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_settle_record.settler_id
     *
     * @return the value of pension_settle_record.settler_id
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public Long getSettlerId() {
        return settlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_settle_record.settler_id
     *
     * @param settlerId the value for pension_settle_record.settler_id
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public void setSettlerId(Long settlerId) {
        this.settlerId = settlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_settle_record.settler_name
     *
     * @return the value of pension_settle_record.settler_name
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public String getSettlerName() {
        return settlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_settle_record.settler_name
     *
     * @param settlerName the value for pension_settle_record.settler_name
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public void setSettlerName(String settlerName) {
        this.settlerName = settlerName == null ? null : settlerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_settle_record.change_time
     *
     * @return the value of pension_settle_record.change_time
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_settle_record.change_time
     *
     * @param changeTime the value for pension_settle_record.change_time
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_settle_record.total_amount
     *
     * @return the value of pension_settle_record.total_amount
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public Double getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_settle_record.total_amount
     *
     * @param totalAmount the value for pension_settle_record.total_amount
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_settle_record.income_amount
     *
     * @return the value of pension_settle_record.income_amount
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public Float getIncomeAmount() {
        return incomeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_settle_record.income_amount
     *
     * @param incomeAmount the value for pension_settle_record.income_amount
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public void setIncomeAmount(Float incomeAmount) {
        this.incomeAmount = incomeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_settle_record.expenses_amount
     *
     * @return the value of pension_settle_record.expenses_amount
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public Float getExpensesAmount() {
        return expensesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_settle_record.expenses_amount
     *
     * @param expensesAmount the value for pension_settle_record.expenses_amount
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public void setExpensesAmount(Float expensesAmount) {
        this.expensesAmount = expensesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_settle_record.settletype_id
     *
     * @return the value of pension_settle_record.settletype_id
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public Long getSettletypeId() {
        return settletypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_settle_record.settletype_id
     *
     * @param settletypeId the value for pension_settle_record.settletype_id
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public void setSettletypeId(Long settletypeId) {
        this.settletypeId = settletypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_settle_record.cleared
     *
     * @return the value of pension_settle_record.cleared
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public Integer getCleared() {
        return cleared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_settle_record.cleared
     *
     * @param cleared the value for pension_settle_record.cleared
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public void setCleared(Integer cleared) {
        this.cleared = cleared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_settle_record.note
     *
     * @return the value of pension_settle_record.note
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_settle_record.note
     *
     * @param note the value for pension_settle_record.note
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_settle_record
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PensionSettleRecord other = (PensionSettleRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSettlerId() == null ? other.getSettlerId() == null : this.getSettlerId().equals(other.getSettlerId()))
            && (this.getSettlerName() == null ? other.getSettlerName() == null : this.getSettlerName().equals(other.getSettlerName()))
            && (this.getChangeTime() == null ? other.getChangeTime() == null : this.getChangeTime().equals(other.getChangeTime()))
            && (this.getTotalAmount() == null ? other.getTotalAmount() == null : this.getTotalAmount().equals(other.getTotalAmount()))
            && (this.getIncomeAmount() == null ? other.getIncomeAmount() == null : this.getIncomeAmount().equals(other.getIncomeAmount()))
            && (this.getExpensesAmount() == null ? other.getExpensesAmount() == null : this.getExpensesAmount().equals(other.getExpensesAmount()))
            && (this.getSettletypeId() == null ? other.getSettletypeId() == null : this.getSettletypeId().equals(other.getSettletypeId()))
            && (this.getCleared() == null ? other.getCleared() == null : this.getCleared().equals(other.getCleared()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_settle_record
     *
     * @mbggenerated Tue Oct 29 15:06:28 GMT+08:00 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSettlerId() == null) ? 0 : getSettlerId().hashCode());
        result = prime * result + ((getSettlerName() == null) ? 0 : getSettlerName().hashCode());
        result = prime * result + ((getChangeTime() == null) ? 0 : getChangeTime().hashCode());
        result = prime * result + ((getTotalAmount() == null) ? 0 : getTotalAmount().hashCode());
        result = prime * result + ((getIncomeAmount() == null) ? 0 : getIncomeAmount().hashCode());
        result = prime * result + ((getExpensesAmount() == null) ? 0 : getExpensesAmount().hashCode());
        result = prime * result + ((getSettletypeId() == null) ? 0 : getSettletypeId().hashCode());
        result = prime * result + ((getCleared() == null) ? 0 : getCleared().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        return result;
    }
}