package domain.financeManage;

import java.io.Serializable;
import java.util.Date;

public class PensionFinancialpayment implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.id
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.startTime
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private Date starttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.dept_id
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private Long deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.deptName
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private String deptname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.endTime
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private Date endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.payee_id
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private Long payeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.payeeName
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private String payeename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.money
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private Float money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.payTime
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private Date paytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.notes
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private String notes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_financialpayment.cleared
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private Integer cleared;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.id
	 * @return  the value of pension_financialpayment.id
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.id
	 * @param id  the value for pension_financialpayment.id
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.startTime
	 * @return  the value of pension_financialpayment.startTime
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public Date getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.startTime
	 * @param starttime  the value for pension_financialpayment.startTime
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.dept_id
	 * @return  the value of pension_financialpayment.dept_id
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public Long getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.dept_id
	 * @param deptId  the value for pension_financialpayment.dept_id
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.deptName
	 * @return  the value of pension_financialpayment.deptName
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public String getDeptname() {
		return deptname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.deptName
	 * @param deptname  the value for pension_financialpayment.deptName
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setDeptname(String deptname) {
		this.deptname = deptname == null ? null : deptname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.endTime
	 * @return  the value of pension_financialpayment.endTime
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.endTime
	 * @param endtime  the value for pension_financialpayment.endTime
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.payee_id
	 * @return  the value of pension_financialpayment.payee_id
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public Long getPayeeId() {
		return payeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.payee_id
	 * @param payeeId  the value for pension_financialpayment.payee_id
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setPayeeId(Long payeeId) {
		this.payeeId = payeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.payeeName
	 * @return  the value of pension_financialpayment.payeeName
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public String getPayeename() {
		return payeename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.payeeName
	 * @param payeename  the value for pension_financialpayment.payeeName
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setPayeename(String payeename) {
		this.payeename = payeename == null ? null : payeename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.money
	 * @return  the value of pension_financialpayment.money
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public Float getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.money
	 * @param money  the value for pension_financialpayment.money
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setMoney(Float money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.payTime
	 * @return  the value of pension_financialpayment.payTime
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public Date getPaytime() {
		return paytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.payTime
	 * @param paytime  the value for pension_financialpayment.payTime
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setPaytime(Date paytime) {
		this.paytime = paytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.notes
	 * @return  the value of pension_financialpayment.notes
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.notes
	 * @param notes  the value for pension_financialpayment.notes
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setNotes(String notes) {
		this.notes = notes == null ? null : notes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_financialpayment.cleared
	 * @return  the value of pension_financialpayment.cleared
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public Integer getCleared() {
		return cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_financialpayment.cleared
	 * @param cleared  the value for pension_financialpayment.cleared
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	public void setCleared(Integer cleared) {
		this.cleared = cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PensionFinancialpayment other = (PensionFinancialpayment) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getStarttime() == null ? other.getStarttime() == null
						: this.getStarttime().equals(other.getStarttime()))
				&& (this.getDeptId() == null ? other.getDeptId() == null : this
						.getDeptId().equals(other.getDeptId()))
				&& (this.getDeptname() == null ? other.getDeptname() == null
						: this.getDeptname().equals(other.getDeptname()))
				&& (this.getEndtime() == null ? other.getEndtime() == null
						: this.getEndtime().equals(other.getEndtime()))
				&& (this.getPayeeId() == null ? other.getPayeeId() == null
						: this.getPayeeId().equals(other.getPayeeId()))
				&& (this.getPayeename() == null ? other.getPayeename() == null
						: this.getPayeename().equals(other.getPayeename()))
				&& (this.getMoney() == null ? other.getMoney() == null : this
						.getMoney().equals(other.getMoney()))
				&& (this.getPaytime() == null ? other.getPaytime() == null
						: this.getPaytime().equals(other.getPaytime()))
				&& (this.getNotes() == null ? other.getNotes() == null : this
						.getNotes().equals(other.getNotes()))
				&& (this.getCleared() == null ? other.getCleared() == null
						: this.getCleared().equals(other.getCleared()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getStarttime() == null) ? 0 : getStarttime().hashCode());
		result = prime * result
				+ ((getDeptId() == null) ? 0 : getDeptId().hashCode());
		result = prime * result
				+ ((getDeptname() == null) ? 0 : getDeptname().hashCode());
		result = prime * result
				+ ((getEndtime() == null) ? 0 : getEndtime().hashCode());
		result = prime * result
				+ ((getPayeeId() == null) ? 0 : getPayeeId().hashCode());
		result = prime * result
				+ ((getPayeename() == null) ? 0 : getPayeename().hashCode());
		result = prime * result
				+ ((getMoney() == null) ? 0 : getMoney().hashCode());
		result = prime * result
				+ ((getPaytime() == null) ? 0 : getPaytime().hashCode());
		result = prime * result
				+ ((getNotes() == null) ? 0 : getNotes().hashCode());
		result = prime * result
				+ ((getCleared() == null) ? 0 : getCleared().hashCode());
		return result;
	}
}