package persistence.receptionManage;

import domain.receptionManage.PensionApplyevaluate;
import domain.receptionManage.PensionApplyevaluateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.receptionManage.PensionEvalDomain;

public interface PensionApplyevaluateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	int countByExample(PensionApplyevaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	int deleteByExample(PensionApplyevaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	int insert(PensionApplyevaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	int insertSelective(PensionApplyevaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	List<PensionApplyevaluate> selectByExample(
			PensionApplyevaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	PensionApplyevaluate selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionApplyevaluate record,
			@Param("example") PensionApplyevaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	int updateByExample(@Param("record") PensionApplyevaluate record,
			@Param("example") PensionApplyevaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionApplyevaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_applyevaluate
	 * 
	 * @mbggenerated Fri Aug 30 10:46:21 CST 2013
	 */
	int updateByPrimaryKey(PensionApplyevaluate record);

	// 查询各部门评估意见
	List<PensionEvalDomain> selecDeptRecords(@Param("applyId") Long applyId,
			@Param("emptId") Long emptId, @Param("deptId") Long deptId);
}