package domain.dictionary;

import java.io.Serializable;

public class PensionDicEvent implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_event.id
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_event.dept_id
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	private Long deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_event.emp_id
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	private Long empId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_event.eventName
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	private String eventname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_event.eventType
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	private Integer eventtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_event.priority
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	private Integer priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_dic_event
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_event.id
	 * @return  the value of pension_dic_event.id
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_event.id
	 * @param id  the value for pension_dic_event.id
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_event.dept_id
	 * @return  the value of pension_dic_event.dept_id
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public Long getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_event.dept_id
	 * @param deptId  the value for pension_dic_event.dept_id
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_event.emp_id
	 * @return  the value of pension_dic_event.emp_id
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public Long getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_event.emp_id
	 * @param empId  the value for pension_dic_event.emp_id
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public void setEmpId(Long empId) {
		this.empId = empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_event.eventName
	 * @return  the value of pension_dic_event.eventName
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public String getEventname() {
		return eventname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_event.eventName
	 * @param eventname  the value for pension_dic_event.eventName
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public void setEventname(String eventname) {
		this.eventname = eventname == null ? null : eventname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_event.eventType
	 * @return  the value of pension_dic_event.eventType
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public Integer getEventtype() {
		return eventtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_event.eventType
	 * @param eventtype  the value for pension_dic_event.eventType
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public void setEventtype(Integer eventtype) {
		this.eventtype = eventtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_event.priority
	 * @return  the value of pension_dic_event.priority
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_event.priority
	 * @param priority  the value for pension_dic_event.priority
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_dic_event
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PensionDicEvent other = (PensionDicEvent) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getDeptId() == null ? other.getDeptId() == null : this
						.getDeptId().equals(other.getDeptId()))
				&& (this.getEmpId() == null ? other.getEmpId() == null : this
						.getEmpId().equals(other.getEmpId()))
				&& (this.getEventname() == null ? other.getEventname() == null
						: this.getEventname().equals(other.getEventname()))
				&& (this.getEventtype() == null ? other.getEventtype() == null
						: this.getEventtype().equals(other.getEventtype()))
				&& (this.getPriority() == null ? other.getPriority() == null
						: this.getPriority().equals(other.getPriority()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_dic_event
	 * @mbggenerated  Fri Feb 07 09:48:41 CST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getDeptId() == null) ? 0 : getDeptId().hashCode());
		result = prime * result
				+ ((getEmpId() == null) ? 0 : getEmpId().hashCode());
		result = prime * result
				+ ((getEventname() == null) ? 0 : getEventname().hashCode());
		result = prime * result
				+ ((getEventtype() == null) ? 0 : getEventtype().hashCode());
		result = prime * result
				+ ((getPriority() == null) ? 0 : getPriority().hashCode());
		return result;
	}
}