package domain.dictionary;

import java.io.Serializable;

public class PensionDicPayway implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_payway.id
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_payway.payway_name
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	private String paywayName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_payway.input_code
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	private String inputCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_payway.payway_mark
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	private String paywayMark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_payway.cleared
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	private Integer cleared;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_payway.note
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_payway.fee
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	private Float fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_dic_payway.pay_fee
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	private String payFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_dic_payway
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_payway.id
	 * @return  the value of pension_dic_payway.id
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_payway.id
	 * @param id  the value for pension_dic_payway.id
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_payway.payway_name
	 * @return  the value of pension_dic_payway.payway_name
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public String getPaywayName() {
		return paywayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_payway.payway_name
	 * @param paywayName  the value for pension_dic_payway.payway_name
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public void setPaywayName(String paywayName) {
		this.paywayName = paywayName == null ? null : paywayName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_payway.input_code
	 * @return  the value of pension_dic_payway.input_code
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public String getInputCode() {
		return inputCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_payway.input_code
	 * @param inputCode  the value for pension_dic_payway.input_code
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public void setInputCode(String inputCode) {
		this.inputCode = inputCode == null ? null : inputCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_payway.payway_mark
	 * @return  the value of pension_dic_payway.payway_mark
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public String getPaywayMark() {
		return paywayMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_payway.payway_mark
	 * @param paywayMark  the value for pension_dic_payway.payway_mark
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public void setPaywayMark(String paywayMark) {
		this.paywayMark = paywayMark == null ? null : paywayMark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_payway.cleared
	 * @return  the value of pension_dic_payway.cleared
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public Integer getCleared() {
		return cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_payway.cleared
	 * @param cleared  the value for pension_dic_payway.cleared
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public void setCleared(Integer cleared) {
		this.cleared = cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_payway.note
	 * @return  the value of pension_dic_payway.note
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_payway.note
	 * @param note  the value for pension_dic_payway.note
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_payway.fee
	 * @return  the value of pension_dic_payway.fee
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public Float getFee() {
		return fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_payway.fee
	 * @param fee  the value for pension_dic_payway.fee
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public void setFee(Float fee) {
		this.fee = fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_dic_payway.pay_fee
	 * @return  the value of pension_dic_payway.pay_fee
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public String getPayFee() {
		return payFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_dic_payway.pay_fee
	 * @param payFee  the value for pension_dic_payway.pay_fee
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	public void setPayFee(String payFee) {
		this.payFee = payFee == null ? null : payFee.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_dic_payway
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PensionDicPayway other = (PensionDicPayway) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getPaywayName() == null ? other.getPaywayName() == null
						: this.getPaywayName().equals(other.getPaywayName()))
				&& (this.getInputCode() == null ? other.getInputCode() == null
						: this.getInputCode().equals(other.getInputCode()))
				&& (this.getPaywayMark() == null ? other.getPaywayMark() == null
						: this.getPaywayMark().equals(other.getPaywayMark()))
				&& (this.getCleared() == null ? other.getCleared() == null
						: this.getCleared().equals(other.getCleared()))
				&& (this.getNote() == null ? other.getNote() == null : this
						.getNote().equals(other.getNote()))
				&& (this.getFee() == null ? other.getFee() == null : this
						.getFee().equals(other.getFee()))
				&& (this.getPayFee() == null ? other.getPayFee() == null : this
						.getPayFee().equals(other.getPayFee()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_dic_payway
	 * @mbggenerated  Mon Dec 09 09:26:38 CST 2013
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getPaywayName() == null) ? 0 : getPaywayName().hashCode());
		result = prime * result
				+ ((getInputCode() == null) ? 0 : getInputCode().hashCode());
		result = prime * result
				+ ((getPaywayMark() == null) ? 0 : getPaywayMark().hashCode());
		result = prime * result
				+ ((getCleared() == null) ? 0 : getCleared().hashCode());
		result = prime * result
				+ ((getNote() == null) ? 0 : getNote().hashCode());
		result = prime * result
				+ ((getFee() == null) ? 0 : getFee().hashCode());
		result = prime * result
				+ ((getPayFee() == null) ? 0 : getPayFee().hashCode());
		return result;
	}
}