package persistence.nurseManage;

import domain.nurseManage.PensionCareAppointment;
import domain.nurseManage.PensionCareAppointmentExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.olderManage.CareAppointmentDomain;

public interface PensionCareAppointmentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	int countByExample(PensionCareAppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	int deleteByExample(PensionCareAppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	int insert(PensionCareAppointment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	int insertSelective(PensionCareAppointment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	List<PensionCareAppointment> selectByExample(
			PensionCareAppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	PensionCareAppointment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	int updateByExampleSelective(
			@Param("record") PensionCareAppointment record,
			@Param("example") PensionCareAppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	int updateByExample(@Param("record") PensionCareAppointment record,
			@Param("example") PensionCareAppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionCareAppointment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_care_appointment
	 * @mbggenerated  Wed Nov 20 15:36:39 CST 2013
	 */
	int updateByPrimaryKey(PensionCareAppointment record);

	/**
	 * 根据条件查询护理预约记录
	 * 
	 * @param olderId
	 * @param startDate
	 * @param endDate
	 * @return
	 */
	List<CareAppointmentDomain> selectCareAppList(
			@Param("olderId") Long olderId, @Param("startDate") Date startDate,
			@Param("endDate") Date endDate,@Param("careAppId") Long careAppId);
}