package domain.fingerPrint;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PensionFingerPrintDailyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public PensionFingerPrintDailyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null || value.toString().equals("")) {
				addCriterion("1=1");
				return;
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null
					|| value1.toString().equals("")
					|| value2.toString().equals("")) {
				addCriterion("1=1");
				return;
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoIsNull() {
			addCriterion("Astr_Serial_No is null");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoIsNotNull() {
			addCriterion("Astr_Serial_No is not null");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoEqualTo(String value) {
			addCriterion("Astr_Serial_No =", value, "astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoNotEqualTo(String value) {
			addCriterion("Astr_Serial_No <>", value, "astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoGreaterThan(String value) {
			addCriterion("Astr_Serial_No >", value, "astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoGreaterThanOrEqualTo(String value) {
			addCriterion("Astr_Serial_No >=", value, "astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoLessThan(String value) {
			addCriterion("Astr_Serial_No <", value, "astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoLessThanOrEqualTo(String value) {
			addCriterion("Astr_Serial_No <=", value, "astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoLike(String value) {
			addCriterion("Astr_Serial_No like", value, "astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoNotLike(String value) {
			addCriterion("Astr_Serial_No not like", value, "astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoIn(List<String> values) {
			addCriterion("Astr_Serial_No in", values, "astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoNotIn(List<String> values) {
			addCriterion("Astr_Serial_No not in", values, "astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoBetween(String value1, String value2) {
			addCriterion("Astr_Serial_No between", value1, value2,
					"astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrSerialNoNotBetween(String value1, String value2) {
			addCriterion("Astr_Serial_No not between", value1, value2,
					"astrSerialNo");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpIsNull() {
			addCriterion("Astr_Device_IP is null");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpIsNotNull() {
			addCriterion("Astr_Device_IP is not null");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpEqualTo(String value) {
			addCriterion("Astr_Device_IP =", value, "astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpNotEqualTo(String value) {
			addCriterion("Astr_Device_IP <>", value, "astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpGreaterThan(String value) {
			addCriterion("Astr_Device_IP >", value, "astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpGreaterThanOrEqualTo(String value) {
			addCriterion("Astr_Device_IP >=", value, "astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpLessThan(String value) {
			addCriterion("Astr_Device_IP <", value, "astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpLessThanOrEqualTo(String value) {
			addCriterion("Astr_Device_IP <=", value, "astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpLike(String value) {
			addCriterion("Astr_Device_IP like", value, "astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpNotLike(String value) {
			addCriterion("Astr_Device_IP not like", value, "astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpIn(List<String> values) {
			addCriterion("Astr_Device_IP in", values, "astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpNotIn(List<String> values) {
			addCriterion("Astr_Device_IP not in", values, "astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpBetween(String value1, String value2) {
			addCriterion("Astr_Device_IP between", value1, value2,
					"astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAstrDeviceIpNotBetween(String value1, String value2) {
			addCriterion("Astr_Device_IP not between", value1, value2,
					"astrDeviceIp");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdIsNull() {
			addCriterion("An_Device_ID is null");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdIsNotNull() {
			addCriterion("An_Device_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdEqualTo(String value) {
			addCriterion("An_Device_ID =", value, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdNotEqualTo(String value) {
			addCriterion("An_Device_ID <>", value, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdGreaterThan(String value) {
			addCriterion("An_Device_ID >", value, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdGreaterThanOrEqualTo(String value) {
			addCriterion("An_Device_ID >=", value, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdLessThan(String value) {
			addCriterion("An_Device_ID <", value, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdLessThanOrEqualTo(String value) {
			addCriterion("An_Device_ID <=", value, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdLike(String value) {
			addCriterion("An_Device_ID like", value, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdNotLike(String value) {
			addCriterion("An_Device_ID not like", value, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdIn(List<String> values) {
			addCriterion("An_Device_ID in", values, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdNotIn(List<String> values) {
			addCriterion("An_Device_ID not in", values, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdBetween(String value1, String value2) {
			addCriterion("An_Device_ID between", value1, value2, "anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnDeviceIdNotBetween(String value1, String value2) {
			addCriterion("An_Device_ID not between", value1, value2,
					"anDeviceId");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberIsNull() {
			addCriterion("An_SEnroll_Number is null");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberIsNotNull() {
			addCriterion("An_SEnroll_Number is not null");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberEqualTo(String value) {
			addCriterion("An_SEnroll_Number =", value, "anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberNotEqualTo(String value) {
			addCriterion("An_SEnroll_Number <>", value, "anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberGreaterThan(String value) {
			addCriterion("An_SEnroll_Number >", value, "anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberGreaterThanOrEqualTo(String value) {
			addCriterion("An_SEnroll_Number >=", value, "anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberLessThan(String value) {
			addCriterion("An_SEnroll_Number <", value, "anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberLessThanOrEqualTo(String value) {
			addCriterion("An_SEnroll_Number <=", value, "anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberLike(String value) {
			addCriterion("An_SEnroll_Number like", value, "anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberNotLike(String value) {
			addCriterion("An_SEnroll_Number not like", value, "anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberIn(List<String> values) {
			addCriterion("An_SEnroll_Number in", values, "anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberNotIn(List<String> values) {
			addCriterion("An_SEnroll_Number not in", values, "anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberBetween(String value1, String value2) {
			addCriterion("An_SEnroll_Number between", value1, value2,
					"anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnSenrollNumberNotBetween(String value1,
				String value2) {
			addCriterion("An_SEnroll_Number not between", value1, value2,
					"anSenrollNumber");
			return (Criteria) this;
		}

		public Criteria andAnLogDateIsNull() {
			addCriterion("An_Log_Date is null");
			return (Criteria) this;
		}

		public Criteria andAnLogDateIsNotNull() {
			addCriterion("An_Log_Date is not null");
			return (Criteria) this;
		}

		public Criteria andAnLogDateEqualTo(Date value) {
			addCriterion("An_Log_Date =", value, "anLogDate");
			return (Criteria) this;
		}

		public Criteria andAnLogDateNotEqualTo(Date value) {
			addCriterion("An_Log_Date <>", value, "anLogDate");
			return (Criteria) this;
		}

		public Criteria andAnLogDateGreaterThan(Date value) {
			addCriterion("An_Log_Date >", value, "anLogDate");
			return (Criteria) this;
		}

		public Criteria andAnLogDateGreaterThanOrEqualTo(Date value) {
			addCriterion("An_Log_Date >=", value, "anLogDate");
			return (Criteria) this;
		}

		public Criteria andAnLogDateLessThan(Date value) {
			addCriterion("An_Log_Date <", value, "anLogDate");
			return (Criteria) this;
		}

		public Criteria andAnLogDateLessThanOrEqualTo(Date value) {
			addCriterion("An_Log_Date <=", value, "anLogDate");
			return (Criteria) this;
		}

		public Criteria andAnLogDateIn(List<Date> values) {
			addCriterion("An_Log_Date in", values, "anLogDate");
			return (Criteria) this;
		}

		public Criteria andAnLogDateNotIn(List<Date> values) {
			addCriterion("An_Log_Date not in", values, "anLogDate");
			return (Criteria) this;
		}

		public Criteria andAnLogDateBetween(Date value1, Date value2) {
			addCriterion("An_Log_Date between", value1, value2, "anLogDate");
			return (Criteria) this;
		}

		public Criteria andAnLogDateNotBetween(Date value1, Date value2) {
			addCriterion("An_Log_Date not between", value1, value2, "anLogDate");
			return (Criteria) this;
		}

		public Criteria andRecordTimeIsNull() {
			addCriterion("Record_Time is null");
			return (Criteria) this;
		}

		public Criteria andRecordTimeIsNotNull() {
			addCriterion("Record_Time is not null");
			return (Criteria) this;
		}

		public Criteria andRecordTimeEqualTo(Date value) {
			addCriterion("Record_Time =", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeNotEqualTo(Date value) {
			addCriterion("Record_Time <>", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeGreaterThan(Date value) {
			addCriterion("Record_Time >", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("Record_Time >=", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeLessThan(Date value) {
			addCriterion("Record_Time <", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeLessThanOrEqualTo(Date value) {
			addCriterion("Record_Time <=", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeIn(List<Date> values) {
			addCriterion("Record_Time in", values, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeNotIn(List<Date> values) {
			addCriterion("Record_Time not in", values, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeBetween(Date value1, Date value2) {
			addCriterion("Record_Time between", value1, value2, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeNotBetween(Date value1, Date value2) {
			addCriterion("Record_Time not between", value1, value2,
					"recordTime");
			return (Criteria) this;
		}

		public Criteria andClearedIsNull() {
			addCriterion("cleared is null");
			return (Criteria) this;
		}

		public Criteria andClearedIsNotNull() {
			addCriterion("cleared is not null");
			return (Criteria) this;
		}

		public Criteria andClearedEqualTo(Integer value) {
			addCriterion("cleared =", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedNotEqualTo(Integer value) {
			addCriterion("cleared <>", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedGreaterThan(Integer value) {
			addCriterion("cleared >", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedGreaterThanOrEqualTo(Integer value) {
			addCriterion("cleared >=", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedLessThan(Integer value) {
			addCriterion("cleared <", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedLessThanOrEqualTo(Integer value) {
			addCriterion("cleared <=", value, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedIn(List<Integer> values) {
			addCriterion("cleared in", values, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedNotIn(List<Integer> values) {
			addCriterion("cleared not in", values, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedBetween(Integer value1, Integer value2) {
			addCriterion("cleared between", value1, value2, "cleared");
			return (Criteria) this;
		}

		public Criteria andClearedNotBetween(Integer value1, Integer value2) {
			addCriterion("cleared not between", value1, value2, "cleared");
			return (Criteria) this;
		}

		public Criteria andNotesIsNull() {
			addCriterion("notes is null");
			return (Criteria) this;
		}

		public Criteria andNotesIsNotNull() {
			addCriterion("notes is not null");
			return (Criteria) this;
		}

		public Criteria andNotesEqualTo(String value) {
			addCriterion("notes =", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotEqualTo(String value) {
			addCriterion("notes <>", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesGreaterThan(String value) {
			addCriterion("notes >", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesGreaterThanOrEqualTo(String value) {
			addCriterion("notes >=", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesLessThan(String value) {
			addCriterion("notes <", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesLessThanOrEqualTo(String value) {
			addCriterion("notes <=", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesLike(String value) {
			addCriterion("notes like", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotLike(String value) {
			addCriterion("notes not like", value, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesIn(List<String> values) {
			addCriterion("notes in", values, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotIn(List<String> values) {
			addCriterion("notes not in", values, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesBetween(String value1, String value2) {
			addCriterion("notes between", value1, value2, "notes");
			return (Criteria) this;
		}

		public Criteria andNotesNotBetween(String value1, String value2) {
			addCriterion("notes not between", value1, value2, "notes");
			return (Criteria) this;
		}

		public Criteria andUsedIsNull() {
			addCriterion("used is null");
			return (Criteria) this;
		}

		public Criteria andUsedIsNotNull() {
			addCriterion("used is not null");
			return (Criteria) this;
		}

		public Criteria andUsedEqualTo(Integer value) {
			addCriterion("used =", value, "used");
			return (Criteria) this;
		}

		public Criteria andUsedNotEqualTo(Integer value) {
			addCriterion("used <>", value, "used");
			return (Criteria) this;
		}

		public Criteria andUsedGreaterThan(Integer value) {
			addCriterion("used >", value, "used");
			return (Criteria) this;
		}

		public Criteria andUsedGreaterThanOrEqualTo(Integer value) {
			addCriterion("used >=", value, "used");
			return (Criteria) this;
		}

		public Criteria andUsedLessThan(Integer value) {
			addCriterion("used <", value, "used");
			return (Criteria) this;
		}

		public Criteria andUsedLessThanOrEqualTo(Integer value) {
			addCriterion("used <=", value, "used");
			return (Criteria) this;
		}

		public Criteria andUsedIn(List<Integer> values) {
			addCriterion("used in", values, "used");
			return (Criteria) this;
		}

		public Criteria andUsedNotIn(List<Integer> values) {
			addCriterion("used not in", values, "used");
			return (Criteria) this;
		}

		public Criteria andUsedBetween(Integer value1, Integer value2) {
			addCriterion("used between", value1, value2, "used");
			return (Criteria) this;
		}

		public Criteria andUsedNotBetween(Integer value1, Integer value2) {
			addCriterion("used not between", value1, value2, "used");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pension_finger_print_daily
	 * @mbggenerated  Fri Sep 27 11:28:39 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pension_finger_print_daily
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 25 15:24:41 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}