package domain.phrManage;

import java.io.Serializable;
import java.util.Date;

public class PensionOlderFamilyill implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_older_familyill.id
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_older_familyill.older_id
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    private Long olderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_older_familyill.older_name
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    private String olderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_older_familyill.familytree_id
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    private Long familytreeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_older_familyill.family_illcode
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    private String familyIllcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_older_familyill.modify_datetime
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    private Date modifyDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pension_older_familyill.cleared
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    private Integer cleared;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pension_older_familyill
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_older_familyill.id
     *
     * @return the value of pension_older_familyill.id
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_older_familyill.id
     *
     * @param id the value for pension_older_familyill.id
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_older_familyill.older_id
     *
     * @return the value of pension_older_familyill.older_id
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public Long getOlderId() {
        return olderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_older_familyill.older_id
     *
     * @param olderId the value for pension_older_familyill.older_id
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public void setOlderId(Long olderId) {
        this.olderId = olderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_older_familyill.older_name
     *
     * @return the value of pension_older_familyill.older_name
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public String getOlderName() {
        return olderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_older_familyill.older_name
     *
     * @param olderName the value for pension_older_familyill.older_name
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public void setOlderName(String olderName) {
        this.olderName = olderName == null ? null : olderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_older_familyill.familytree_id
     *
     * @return the value of pension_older_familyill.familytree_id
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public Long getFamilytreeId() {
        return familytreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_older_familyill.familytree_id
     *
     * @param familytreeId the value for pension_older_familyill.familytree_id
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public void setFamilytreeId(Long familytreeId) {
        this.familytreeId = familytreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_older_familyill.family_illcode
     *
     * @return the value of pension_older_familyill.family_illcode
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public String getFamilyIllcode() {
        return familyIllcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_older_familyill.family_illcode
     *
     * @param familyIllcode the value for pension_older_familyill.family_illcode
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public void setFamilyIllcode(String familyIllcode) {
        this.familyIllcode = familyIllcode == null ? null : familyIllcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_older_familyill.modify_datetime
     *
     * @return the value of pension_older_familyill.modify_datetime
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public Date getModifyDatetime() {
        return modifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_older_familyill.modify_datetime
     *
     * @param modifyDatetime the value for pension_older_familyill.modify_datetime
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public void setModifyDatetime(Date modifyDatetime) {
        this.modifyDatetime = modifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pension_older_familyill.cleared
     *
     * @return the value of pension_older_familyill.cleared
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public Integer getCleared() {
        return cleared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pension_older_familyill.cleared
     *
     * @param cleared the value for pension_older_familyill.cleared
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    public void setCleared(Integer cleared) {
        this.cleared = cleared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_older_familyill
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PensionOlderFamilyill other = (PensionOlderFamilyill) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOlderId() == null ? other.getOlderId() == null : this.getOlderId().equals(other.getOlderId()))
            && (this.getOlderName() == null ? other.getOlderName() == null : this.getOlderName().equals(other.getOlderName()))
            && (this.getFamilytreeId() == null ? other.getFamilytreeId() == null : this.getFamilytreeId().equals(other.getFamilytreeId()))
            && (this.getFamilyIllcode() == null ? other.getFamilyIllcode() == null : this.getFamilyIllcode().equals(other.getFamilyIllcode()))
            && (this.getModifyDatetime() == null ? other.getModifyDatetime() == null : this.getModifyDatetime().equals(other.getModifyDatetime()))
            && (this.getCleared() == null ? other.getCleared() == null : this.getCleared().equals(other.getCleared()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_older_familyill
     *
     * @mbggenerated Thu Dec 05 13:20:45 CST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOlderId() == null) ? 0 : getOlderId().hashCode());
        result = prime * result + ((getOlderName() == null) ? 0 : getOlderName().hashCode());
        result = prime * result + ((getFamilytreeId() == null) ? 0 : getFamilytreeId().hashCode());
        result = prime * result + ((getFamilyIllcode() == null) ? 0 : getFamilyIllcode().hashCode());
        result = prime * result + ((getModifyDatetime() == null) ? 0 : getModifyDatetime().hashCode());
        result = prime * result + ((getCleared() == null) ? 0 : getCleared().hashCode());
        return result;
    }
}