package persistence.olderManage;

import domain.olderManage.PensionItemcount;
import domain.olderManage.PensionItemcountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.olderManage.PensionItemcountExtend;

public interface PensionItemcountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	int countByExample(PensionItemcountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	int deleteByExample(PensionItemcountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	int insert(PensionItemcount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	int insertSelective(PensionItemcount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	List<PensionItemcount> selectByExample(PensionItemcountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	PensionItemcount selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionItemcount record,
			@Param("example") PensionItemcountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	int updateByExample(@Param("record") PensionItemcount record,
			@Param("example") PensionItemcountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionItemcount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_itemcount
	 * @mbggenerated  Mon Sep 09 19:04:16 CST 2013
	 */
	int updateByPrimaryKey(PensionItemcount record);
	/**
	 * 根据分组id来查询出其对应的项目 和人数
	 * @param id
	 * @return
	 */
	List<PensionItemcountExtend> selectMedicalItemRecord(@Param("groupId")Long groupId);
}