package persistence.olderManage;

import domain.olderManage.PensionDiagnosis;
import domain.olderManage.PensionDiagnosisExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.olderManage.PensionDiagnoseDomain;

public interface PensionDiagnosisMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	int countByExample(PensionDiagnosisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	int deleteByExample(PensionDiagnosisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	int insert(PensionDiagnosis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	int insertSelective(PensionDiagnosis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	List<PensionDiagnosis> selectByExample(PensionDiagnosisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	PensionDiagnosis selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionDiagnosis record,
			@Param("example") PensionDiagnosisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	int updateByExample(@Param("record") PensionDiagnosis record,
			@Param("example") PensionDiagnosisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionDiagnosis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_diagnosis
	 * 
	 * @mbggenerated Mon Oct 07 09:46:40 CST 2013
	 */
	int updateByPrimaryKey(PensionDiagnosis record);

	// 查询医生巡诊记录
	List<PensionDiagnoseDomain> selectDiagnoseRecords(
			@Param("olderId") Long olderId, @Param("startDate") Date startDate,
			@Param("endDate") Date endDate);

	List<PensionDiagnosis> selectExtendByExample(
			@Param("example") PensionDiagnosisExample example,
			@Param("orderByClause") String orderByClause,
			@Param("firstRec") Long firstRec, @Param("pageSize") Long pageSize);
}