package persistence.olderManage;

import domain.olderManage.PensionOlderRecure;
import domain.olderManage.PensionOlderRecureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.olderManage.PensionOlderRecureExtend;

public interface PensionOlderRecureMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	int countByExample(PensionOlderRecureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	int deleteByExample(PensionOlderRecureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	int insert(PensionOlderRecure record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	int insertSelective(PensionOlderRecure record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	List<PensionOlderRecure> selectByExample(PensionOlderRecureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	PensionOlderRecure selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionOlderRecure record,
			@Param("example") PensionOlderRecureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	int updateByExample(@Param("record") PensionOlderRecure record,
			@Param("example") PensionOlderRecureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionOlderRecure record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_older_recure
	 * @mbggenerated  Sat Nov 23 15:09:04 CST 2013
	 */
	int updateByPrimaryKey(PensionOlderRecure record);

	List<PensionOlderRecureExtend> selectExtendByExample(PensionOlderRecureExample example);
}