package persistence.olderManage;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import service.olderManage.LivingRecordDomain;
import service.olderManage.PensionFamilyDomain;
import service.system.NurseEchartsDeman;
import domain.olderManage.PensionLivingrecord;
import domain.olderManage.PensionLivingrecordExample;
import domain.reportManage.OlderLiquidityReport;

public interface PensionLivingrecordMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	int countByExample(PensionLivingrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	int deleteByExample(PensionLivingrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	int insert(PensionLivingrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	int insertSelective(PensionLivingrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	List<PensionLivingrecord> selectByExample(PensionLivingrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	PensionLivingrecord selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	int updateByExampleSelective(@Param("record") PensionLivingrecord record,
			@Param("example") PensionLivingrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	int updateByExample(@Param("record") PensionLivingrecord record,
			@Param("example") PensionLivingrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	int updateByPrimaryKeySelective(PensionLivingrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_livingrecord
	 * @mbggenerated  Mon Mar 10 14:02:40 CST 2014
	 */
	int updateByPrimaryKey(PensionLivingrecord record);

	// 根据条件查询老人的入住记录
	List<LivingRecordDomain> selectLivingRecords(
			@Param("olderId") Long olderId, @Param("startDate") Date StartDate,
			@Param("endDate") Date endDate,@Param("categary") int categary);

	// 根据老人ID查询老人的入住记录
	LivingRecordDomain selectLivingRecordsByOlderId(
			@Param("olderId") Long olderId);

	// 根据老人ID查询待质检的老人信息
	LivingRecordDomain selectCheckOlderByOlderId(@Param("olderId") Long olderId);

	// 查询老人家属列表
	List<PensionFamilyDomain> selectFamily(@Param("olderId") Long olderId);

	// 查询 责任护理员人数
	int countByDistinctNurseId();

	// 查询起止时间内新入院老人数 Mary 2013-12-02
	int selectNewInNum(@Param("startDate") Date startDate,
			@Param("endDate") Date endDate);

	// 查找起止时间内 的老人情况
	List<OlderLiquidityReport> selectOlderLiquidityReports(
			@Param("flag") Integer flag, @Param("startDate") Date startDate,
			@Param("endDate") Date endDate);

	//查找指定起止时间内 指定护理员的护理老人列表
	List<NurseEchartsDeman> selectNurseList(@Param("userId")Long userId);
}