package persistence.olderManage;

import domain.olderManage.PensionLeave;
import domain.olderManage.PensionLeaveExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import service.olderManage.PensionLeaveExtend;

public interface PensionLeaveMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	int countByExample(PensionLeaveExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	int deleteByExample(PensionLeaveExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	int insert(PensionLeave record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	int insertSelective(PensionLeave record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	List<PensionLeave> selectByExample(PensionLeaveExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	PensionLeave selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	int updateByExampleSelective(@Param("record") PensionLeave record,
			@Param("example") PensionLeaveExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	int updateByExample(@Param("record") PensionLeave record,
			@Param("example") PensionLeaveExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	int updateByPrimaryKeySelective(PensionLeave record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_leave
	 * @mbggenerated  Tue Feb 25 15:17:47 CST 2014
	 */
	int updateByPrimaryKey(PensionLeave record);
	/**
	 * 根据封装到map中 登记起始时间和登记截止时间和 老人Id来查询老人登记记录
	 * @param map
	 * @return
	 */
	List<PensionLeaveExtend> selectVacationApplicationRecords(Map<String, Object> map);
	/**
	 * 根据查询条件 来查询自己要处理的 假期申请记录
	 * @param map
	 * @return
	 */
	List<PensionLeaveExtend> selectMyVacationApplicationRecords(Map<String, Object> map);
	/**
	 * 根据老人Id查询出其对应的楼层 大厦 放假 床位等信息
	 * @param olderId 
	 * @return
	 */
	List<PensionLeaveExtend> fillField(@Param("olderId")Long olderId);
	
	
}