package persistence.olderManage;

import domain.olderManage.PensionNotbackontime;
import domain.olderManage.PensionNotbackontimeExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import service.olderManage.PensionNotbackontimeExtend;

public interface PensionNotbackontimeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	int countByExample(PensionNotbackontimeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	int deleteByExample(PensionNotbackontimeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	int insert(PensionNotbackontime record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	int insertSelective(PensionNotbackontime record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	List<PensionNotbackontime> selectByExample(
			PensionNotbackontimeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	PensionNotbackontime selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionNotbackontime record,
			@Param("example") PensionNotbackontimeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	int updateByExample(@Param("record") PensionNotbackontime record,
			@Param("example") PensionNotbackontimeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionNotbackontime record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_notbackontime
	 * @mbggenerated  Fri Aug 30 11:28:06 CST 2013
	 */
	int updateByPrimaryKey(PensionNotbackontime record);
	/**
	 * 根据预返院时间 来查询未按时返院记录
	 * @param map
	 * @return
	 */
	List<PensionNotbackontimeExtend> selectLateOlderRecords(Map<String, Object> map);
	/**
	 * 根据老人ID返回相应的大厦号，房间号等等
	 * @param olderId
	 * @return
	 */
	List<PensionNotbackontimeExtend> fillField(@Param("olderId")Long olderId);
}