package persistence.olderManage;

import domain.olderManage.PensionLivingnotify;
import domain.olderManage.PensionLivingnotifyExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.olderManage.PensionNoticeDomain;

public interface PensionLivingnotifyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	int countByExample(PensionLivingnotifyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	int deleteByExample(PensionLivingnotifyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	int insert(PensionLivingnotify record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	int insertSelective(PensionLivingnotify record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	List<PensionLivingnotify> selectByExample(PensionLivingnotifyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	PensionLivingnotify selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	int updateByExampleSelective(@Param("record") PensionLivingnotify record,
			@Param("example") PensionLivingnotifyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	int updateByExample(@Param("record") PensionLivingnotify record,
			@Param("example") PensionLivingnotifyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	int updateByPrimaryKeySelective(PensionLivingnotify record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pension_livingnotify
	 * 
	 * @mbggenerated Mon Feb 24 14:04:59 CST 2014
	 */
	int updateByPrimaryKey(PensionLivingnotify record);

	// 查询部门未处理处理事件
	List<PensionNoticeDomain> selectUnDealEventList(
			@Param("deptId") Long deptId, @Param("olderId") Long olderId,
			@Param("startDate") Date startDate, @Param("endDate") Date endDate,
			@Param("handleFlag") String handleFlag);

	// 查询老人未质检事件
	List<PensionNoticeDomain> selectUnCheckEventList(
			@Param("olderId") Long olderId, @Param("startDate") Date startDate,
			@Param("endDate") Date endDate, @Param("checkFlag") String checkFlag);

	// 查询老人已质检事件
	List<PensionNoticeDomain> selectCheckEventList(
			@Param("olderId") Long olderId, @Param("startDate") Date startDate,
			@Param("endDate") Date endDate);

}