package persistence.logisticsManage;

import domain.logisticsManage.PensionHaircutApply;
import domain.logisticsManage.PensionHaircutApplyExample;
import domain.logisticsManage.PensionHaircutApplyExtend;

import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionHaircutApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int countByExample(PensionHaircutApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int deleteByExample(PensionHaircutApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int insert(PensionHaircutApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int insertSelective(PensionHaircutApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    List<PensionHaircutApply> selectByExample(PensionHaircutApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    PensionHaircutApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByExampleSelective(@Param("record") PensionHaircutApply record, @Param("example") PensionHaircutApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByExample(@Param("record") PensionHaircutApply record, @Param("example") PensionHaircutApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByPrimaryKeySelective(PensionHaircutApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_haircut_apply
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByPrimaryKey(PensionHaircutApply record);

	ArrayList<PensionHaircutApplyExtend> selectReservedOlderDetails(@Param("scheduleId")Long scheduleId);
}