package persistence.logisticsManage;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import service.logisticsManage.PensionRepairExtend;
import service.logisticsManage.RepairCount;
import domain.logisticsManage.PensionRepair;
import domain.logisticsManage.PensionRepairExample;

public interface PensionRepairMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	int countByExample(PensionRepairExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	int deleteByExample(PensionRepairExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	int insert(PensionRepair record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	int insertSelective(PensionRepair record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	List<PensionRepair> selectByExample(PensionRepairExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	PensionRepair selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	int updateByExampleSelective(@Param("record") PensionRepair record,
			@Param("example") PensionRepairExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	int updateByExample(@Param("record") PensionRepair record,
			@Param("example") PensionRepairExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	int updateByPrimaryKeySelective(PensionRepair record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_repair
	 * @mbggenerated  Mon Mar 03 10:25:25 CST 2014
	 */
	int updateByPrimaryKey(PensionRepair record);
	/**
     * 根据查询条件，查询出对应的维修记录
     * @param map
     * @return
     */
	List<PensionRepairExtend> selectRepairApplicationRecords(Map<String, Object> map);
	/**
	 * 根据查询条件，查询出对应的维修次数
	 * @param map
	 * @return
	 */
	List<RepairCount> selectRepairCountRecords(
			HashMap<String, Object> map);
	
	/**
	 * 根据起止时间查询维修记录 add by mary 2013-12-02
	 * @param startDate
	 * @param endDate
	 * @param sortClass 
	 * @return
	 */
	List<RepairCount> selectRepairRecordByDate(@Param("startDate")Date startDate,@Param("endDate")Date endDate, @Param("sortClass")String sortClass);
}