package persistence.logisticsManage;

import domain.logisticsManage.PensionGoodsDetail;
import domain.logisticsManage.PensionGoodsDetailExample;
import domain.stockManage.PensionStorage;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.stockManage.StorageOutDetailDomain;

public interface PensionGoodsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int countByExample(PensionGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int deleteByExample(PensionGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int insert(PensionGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int insertSelective(PensionGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    List<PensionGoodsDetail> selectByExample(PensionGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    PensionGoodsDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByExampleSelective(@Param("record") PensionGoodsDetail record, @Param("example") PensionGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByExample(@Param("record") PensionGoodsDetail record, @Param("example") PensionGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByPrimaryKeySelective(PensionGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_goods_detail
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByPrimaryKey(PensionGoodsDetail record);
    /**
     * 根据查询条件 查询出对应的消耗量
     * @param map
     * @return
     */
	List<PensionGoodsDetail> selectConsumptionRecords(
			HashMap<String, Object> map);
   
	/**
	 * 根据查询条件 查询出对应的剩余量
	 * @param map
	 * @return
	 */
	List<PensionGoodsDetail> selectRemainRecords(HashMap<String, Object> map);
	
	 /**
     * 根据查询条件 查询出物资出库量
     * @param map
     * @return
     */
	List<StorageOutDetailDomain> selectStorageoutRecords(
			HashMap<String, Object> map);
	/**
	 * 根据查询条件 查询库存
	 * @param map
	 * @return
	 */
	List<PensionStorage> selectStorageRecords(HashMap<String, Object> map);
}