package persistence.logisticsManage;

import domain.logisticsManage.PensionVehicle;
import domain.logisticsManage.PensionVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int countByExample(PensionVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int deleteByExample(PensionVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int insert(PensionVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int insertSelective(PensionVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    List<PensionVehicle> selectByExample(PensionVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    PensionVehicle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByExampleSelective(@Param("record") PensionVehicle record, @Param("example") PensionVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByExample(@Param("record") PensionVehicle record, @Param("example") PensionVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByPrimaryKeySelective(PensionVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_vehicle
     *
     * @mbggenerated Tue Oct 29 15:30:49 GMT+08:00 2013
     */
    int updateByPrimaryKey(PensionVehicle record);
    /**
     * @author bill
     * @date 2013-11-7
     * @name selectByCarNumber
     */
    List<PensionVehicle> selectByCarNumber(@Param("carNumber") String carNumber);
}