package persistence.logisticsManage;

import domain.logisticsManage.PensionMoveApplyExtend;
import domain.logisticsManage.PensionMoveApproval;
import domain.logisticsManage.PensionMoveApprovalExample;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PensionMoveApprovalMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	int countByExample(PensionMoveApprovalExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	int deleteByExample(PensionMoveApprovalExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	int insert(PensionMoveApproval record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	int insertSelective(PensionMoveApproval record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	List<PensionMoveApproval> selectByExample(PensionMoveApprovalExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	PensionMoveApproval selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionMoveApproval record,
			@Param("example") PensionMoveApprovalExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	int updateByExample(@Param("record") PensionMoveApproval record,
			@Param("example") PensionMoveApprovalExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionMoveApproval record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_move_approval
	 * @mbggenerated  Thu Dec 05 10:40:21 CST 2013
	 */
	int updateByPrimaryKey(PensionMoveApproval record);
	/**
     * 根据查询条件查询出对应的搬家申请记录
     * @param map
     * @return
     */
	List<PensionMoveApplyExtend> selectMoveApplicationRecords(
			HashMap<String, Object> map);
	/**
	 * 审批搬家申请记录，更新其字段
	 * @param map
	 */
	void check(Map<String, Object> map);
}