package persistence.dictionary;

import domain.dictionary.PensionDicPayment;
import domain.dictionary.PensionDicPaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionDicPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int countByExample(PensionDicPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int deleteByExample(PensionDicPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int insert(PensionDicPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int insertSelective(PensionDicPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    List<PensionDicPayment> selectByExample(PensionDicPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    PensionDicPayment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByExampleSelective(@Param("record") PensionDicPayment record, @Param("example") PensionDicPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByExample(@Param("record") PensionDicPayment record, @Param("example") PensionDicPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByPrimaryKeySelective(PensionDicPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_payment
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByPrimaryKey(PensionDicPayment record);
}