package persistence.dictionary;

import domain.dictionary.PensionDicSettletype;
import domain.dictionary.PensionDicSettletypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionDicSettletypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int countByExample(PensionDicSettletypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int deleteByExample(PensionDicSettletypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int insert(PensionDicSettletype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int insertSelective(PensionDicSettletype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    List<PensionDicSettletype> selectByExample(PensionDicSettletypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    PensionDicSettletype selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int updateByExampleSelective(@Param("record") PensionDicSettletype record, @Param("example") PensionDicSettletypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int updateByExample(@Param("record") PensionDicSettletype record, @Param("example") PensionDicSettletypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int updateByPrimaryKeySelective(PensionDicSettletype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_settletype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int updateByPrimaryKey(PensionDicSettletype record);
}