package persistence.dictionary;

import domain.dictionary.PensionDicOtheranamnesis;
import domain.dictionary.PensionDicOtheranamnesisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionDicOtheranamnesisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int countByExample(PensionDicOtheranamnesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int deleteByExample(PensionDicOtheranamnesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int insert(PensionDicOtheranamnesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int insertSelective(PensionDicOtheranamnesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    List<PensionDicOtheranamnesis> selectByExample(PensionDicOtheranamnesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    PensionDicOtheranamnesis selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByExampleSelective(@Param("record") PensionDicOtheranamnesis record, @Param("example") PensionDicOtheranamnesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByExample(@Param("record") PensionDicOtheranamnesis record, @Param("example") PensionDicOtheranamnesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByPrimaryKeySelective(PensionDicOtheranamnesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_otheranamnesis
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByPrimaryKey(PensionDicOtheranamnesis record);
}