package persistence.dictionary;

import domain.dictionary.PensionDictRefundtype;
import domain.dictionary.PensionDictRefundtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionDictRefundtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int countByExample(PensionDictRefundtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int deleteByExample(PensionDictRefundtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int insert(PensionDictRefundtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int insertSelective(PensionDictRefundtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    List<PensionDictRefundtype> selectByExample(PensionDictRefundtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    PensionDictRefundtype selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int updateByExampleSelective(@Param("record") PensionDictRefundtype record, @Param("example") PensionDictRefundtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int updateByExample(@Param("record") PensionDictRefundtype record, @Param("example") PensionDictRefundtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int updateByPrimaryKeySelective(PensionDictRefundtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dict_refundtype
     *
     * @mbggenerated Tue Oct 29 16:05:42 GMT+08:00 2013
     */
    int updateByPrimaryKey(PensionDictRefundtype record);
}