package persistence.dictionary;

import domain.dictionary.PensionDicAllergy;
import domain.dictionary.PensionDicAllergyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionDicAllergyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int countByExample(PensionDicAllergyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int deleteByExample(PensionDicAllergyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int insert(PensionDicAllergy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int insertSelective(PensionDicAllergy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    List<PensionDicAllergy> selectByExample(PensionDicAllergyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    PensionDicAllergy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByExampleSelective(@Param("record") PensionDicAllergy record, @Param("example") PensionDicAllergyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByExample(@Param("record") PensionDicAllergy record, @Param("example") PensionDicAllergyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByPrimaryKeySelective(PensionDicAllergy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_allergy
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByPrimaryKey(PensionDicAllergy record);
}