package persistence.dictionary;

import domain.dictionary.PensionDicRecureItem;
import domain.dictionary.PensionDicRecureItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionDicRecureItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    int countByExample(PensionDicRecureItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    int deleteByExample(PensionDicRecureItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    int insert(PensionDicRecureItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    int insertSelective(PensionDicRecureItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    List<PensionDicRecureItem> selectByExample(PensionDicRecureItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    PensionDicRecureItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    int updateByExampleSelective(@Param("record") PensionDicRecureItem record, @Param("example") PensionDicRecureItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    int updateByExample(@Param("record") PensionDicRecureItem record, @Param("example") PensionDicRecureItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(PensionDicRecureItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_recure_item
     *
     * @mbggenerated Thu Oct 10 17:36:30 CST 2013
     */
    int updateByPrimaryKey(PensionDicRecureItem record);
}