package persistence.dictionary;

import domain.dictionary.PensionDicRelationship;
import domain.dictionary.PensionDicRelationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionDicRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    int countByExample(PensionDicRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    int deleteByExample(PensionDicRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    int insert(PensionDicRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    int insertSelective(PensionDicRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    List<PensionDicRelationship> selectByExample(PensionDicRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    PensionDicRelationship selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    int updateByExampleSelective(@Param("record") PensionDicRelationship record, @Param("example") PensionDicRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    int updateByExample(@Param("record") PensionDicRelationship record, @Param("example") PensionDicRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    int updateByPrimaryKeySelective(PensionDicRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_relationship
     *
     * @mbggenerated Thu Aug 29 15:35:28 CST 2013
     */
    int updateByPrimaryKey(PensionDicRelationship record);
}