package persistence.dictionary;

import domain.dictionary.PensionDicFamilytree;
import domain.dictionary.PensionDicFamilytreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionDicFamilytreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int countByExample(PensionDicFamilytreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int deleteByExample(PensionDicFamilytreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int insert(PensionDicFamilytree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int insertSelective(PensionDicFamilytree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    List<PensionDicFamilytree> selectByExample(PensionDicFamilytreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    PensionDicFamilytree selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByExampleSelective(@Param("record") PensionDicFamilytree record, @Param("example") PensionDicFamilytreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByExample(@Param("record") PensionDicFamilytree record, @Param("example") PensionDicFamilytreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByPrimaryKeySelective(PensionDicFamilytree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pension_dic_familytree
     *
     * @mbggenerated Thu Dec 05 13:20:52 CST 2013
     */
    int updateByPrimaryKey(PensionDicFamilytree record);
}