package persistence.caterManage;

import domain.caterManage.PensionFoodIngredient;
import domain.caterManage.PensionFoodIngredientExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import controller.caterManage.ExtendForCostAnalysis;

public interface PensionFoodIngredientMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	int countByExample(PensionFoodIngredientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	int deleteByExample(PensionFoodIngredientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	int insert(PensionFoodIngredient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	int insertSelective(PensionFoodIngredient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	List<PensionFoodIngredient> selectByExample(
			PensionFoodIngredientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	PensionFoodIngredient selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionFoodIngredient record,
			@Param("example") PensionFoodIngredientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	int updateByExample(@Param("record") PensionFoodIngredient record,
			@Param("example") PensionFoodIngredientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionFoodIngredient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_food_ingredient
	 * @mbggenerated  Wed Dec 04 11:34:33 CST 2013
	 */
	int updateByPrimaryKey(PensionFoodIngredient record);

	/**
     * 
    * @Title: selectCostAnalysisRecord 
    * @Description: 菜品成本统计查询汇总
    * @param @return
    * @return List<ExtendForCostAnalysis>
    * @throws 
    * @author Justin.Su
    * @date 2013-9-9 下午2:12:16
    * @version V1.0
     */
    List<ExtendForCostAnalysis> selectCostAnalysisRecord();
    
    /**
     * 
    * @Title: selectCostAnalysisRecord 
    * @Description: 菜品成本统计查询汇总(根据条件)
    * @param @param menuId
    * @param @return
    * @return List<ExtendForCostAnalysis>
    * @throws 
    * @author Justin.Su
    * @date 2013-9-9 下午1:54:32
    * @version V1.0
     */
    List<ExtendForCostAnalysis> selectCostAnalysisRecordByCondition(@Param("menuId") Long menuId,@Param("startDate") Date startDate,@Param("endDate") Date endDate);
}