package persistence.caterManage;

import domain.caterManage.PensionFoodmenu;
import domain.caterManage.PensionFoodmenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionFoodmenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int countByExample(PensionFoodmenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int deleteByExample(PensionFoodmenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int insert(PensionFoodmenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int insertSelective(PensionFoodmenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	List<PensionFoodmenu> selectByExampleWithBLOBs(
			PensionFoodmenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	List<PensionFoodmenu> selectByExample(PensionFoodmenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	PensionFoodmenu selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionFoodmenu record,
			@Param("example") PensionFoodmenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") PensionFoodmenu record,
			@Param("example") PensionFoodmenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int updateByExample(@Param("record") PensionFoodmenu record,
			@Param("example") PensionFoodmenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionFoodmenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(PensionFoodmenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_foodmenu
	 * @mbggenerated  Thu Dec 12 14:09:12 CST 2013
	 */
	int updateByPrimaryKey(PensionFoodmenu record);
}