package persistence.caterManage;

import domain.caterManage.PensionOrder;
import domain.caterManage.PensionOrderExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.junit.runners.Parameterized.Parameters;

public interface PensionOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	int countByExample(PensionOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	int deleteByExample(PensionOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	int insert(PensionOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	int insertSelective(PensionOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	List<PensionOrder> selectByExample(PensionOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	PensionOrder selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionOrder record,
			@Param("example") PensionOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	int updateByExample(@Param("record") PensionOrder record,
			@Param("example") PensionOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_order
	 * @mbggenerated  Sun Nov 10 11:01:52 CST 2013
	 */
	int updateByPrimaryKey(PensionOrder record);

	/**
	 * 
	* @Title: selectByExampleLimit 
	* @Description: TODO
	* @param @param olderId
	* @param @param eatDate
	* @param @return
	* @return List<PensionOrder>
	* @throws 
	* @author Justin.Su
	* @date 2013-9-24 上午9:26:45
	* @version V1.0
	 * @param sendFlag 
	 * @param isConfirm 
	 */
	List<PensionOrder> selectByExampleLimit(@Param("olderId") Long olderId,@Param("eatDate") Date eatDate, @Param("sendFlag")int sendFlag, @Param("isConfirm")Integer isConfirm);
	
	/**
	 * 
	* @Title: selectOrderedListByCondition 
	* @Description: TODO
	* @param @param olderId
	* @param @param startDate
	* @param @param endDate
	* @param @param payFlag
	* @param @param confirmFlag
	* @param @return
	* @return List<PensionOrder>
	* @throws 
	* @author Justin.Su
	* @date 2013-9-24 上午10:33:48
	* @version V1.0
	 */
	List<PensionOrder> selectOrderedListByCondition(@Param("olderId") Long olderId,@Param("startDate") Date startDate,@Param("endDate") Date endDate,@Param("payFlag") Long payFlag,@Param("confirmFlag") Long confirmFlag);
}