package persistence.system;

import domain.system.PensionSysUser;
import domain.system.PensionSysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import service.system.PensionSysUserDoman;

public interface PensionSysUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	int countByExample(PensionSysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	int deleteByExample(PensionSysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	int insert(PensionSysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	int insertSelective(PensionSysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	List<PensionSysUser> selectByExample(PensionSysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	PensionSysUser selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionSysUser record,
			@Param("example") PensionSysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	int updateByExample(@Param("record") PensionSysUser record,
			@Param("example") PensionSysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionSysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_sys_user
	 * @mbggenerated  Mon Sep 09 16:24:02 CST 2013
	 */
	int updateByPrimaryKey(PensionSysUser record);
	
	
	List<PensionSysUserDoman> selectExtendByExample(PensionSysUserExample example);
	
}