package domain.hrManage;

import java.io.Serializable;
import java.util.Date;

public class PensionArrangeTemplate implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_arrange_template.id
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_arrange_template.template_name
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	private String templateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_arrange_template.dept_id
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	private Long deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_arrange_template.dept_name
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	private String deptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_arrange_template.note
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pension_arrange_template.cleared
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	private Integer cleared;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pension_arrange_template
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_arrange_template.id
	 * @return  the value of pension_arrange_template.id
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_arrange_template.id
	 * @param id  the value for pension_arrange_template.id
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_arrange_template.template_name
	 * @return  the value of pension_arrange_template.template_name
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public String getTemplateName() {
		return templateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_arrange_template.template_name
	 * @param templateName  the value for pension_arrange_template.template_name
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public void setTemplateName(String templateName) {
		this.templateName = templateName == null ? null : templateName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_arrange_template.dept_id
	 * @return  the value of pension_arrange_template.dept_id
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public Long getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_arrange_template.dept_id
	 * @param deptId  the value for pension_arrange_template.dept_id
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_arrange_template.dept_name
	 * @return  the value of pension_arrange_template.dept_name
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_arrange_template.dept_name
	 * @param deptName  the value for pension_arrange_template.dept_name
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName == null ? null : deptName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_arrange_template.note
	 * @return  the value of pension_arrange_template.note
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_arrange_template.note
	 * @param note  the value for pension_arrange_template.note
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pension_arrange_template.cleared
	 * @return  the value of pension_arrange_template.cleared
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public Integer getCleared() {
		return cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pension_arrange_template.cleared
	 * @param cleared  the value for pension_arrange_template.cleared
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	public void setCleared(Integer cleared) {
		this.cleared = cleared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_arrange_template
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PensionArrangeTemplate other = (PensionArrangeTemplate) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getTemplateName() == null ? other.getTemplateName() == null
						: this.getTemplateName()
								.equals(other.getTemplateName()))
				&& (this.getDeptId() == null ? other.getDeptId() == null : this
						.getDeptId().equals(other.getDeptId()))
				&& (this.getDeptName() == null ? other.getDeptName() == null
						: this.getDeptName().equals(other.getDeptName()))
				&& (this.getNote() == null ? other.getNote() == null : this
						.getNote().equals(other.getNote()))
				&& (this.getCleared() == null ? other.getCleared() == null
						: this.getCleared().equals(other.getCleared()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_arrange_template
	 * @mbggenerated  Fri Mar 14 10:52:34 CST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime
				* result
				+ ((getTemplateName() == null) ? 0 : getTemplateName()
						.hashCode());
		result = prime * result
				+ ((getDeptId() == null) ? 0 : getDeptId().hashCode());
		result = prime * result
				+ ((getDeptName() == null) ? 0 : getDeptName().hashCode());
		result = prime * result
				+ ((getNote() == null) ? 0 : getNote().hashCode());
		result = prime * result
				+ ((getCleared() == null) ? 0 : getCleared().hashCode());
		return result;
	}
}