package persistence.reportManage;

import domain.reportManage.PensionBuildingStaffamount;
import domain.reportManage.PensionBuildingStaffamountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionBuildingStaffamountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	int countByExample(PensionBuildingStaffamountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	int deleteByExample(PensionBuildingStaffamountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	int insert(PensionBuildingStaffamount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	int insertSelective(PensionBuildingStaffamount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	List<PensionBuildingStaffamount> selectByExample(
			PensionBuildingStaffamountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	PensionBuildingStaffamount selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	int updateByExampleSelective(
			@Param("record") PensionBuildingStaffamount record,
			@Param("example") PensionBuildingStaffamountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	int updateByExample(@Param("record") PensionBuildingStaffamount record,
			@Param("example") PensionBuildingStaffamountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionBuildingStaffamount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_building_staffamount
	 * @mbggenerated  Sat Nov 16 11:28:35 CST 2013
	 */
	int updateByPrimaryKey(PensionBuildingStaffamount record);
}