package persistence.financeManage;

import domain.financeManage.PensionPaymentdetail;
import domain.financeManage.PensionPaymentdetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionPaymentdetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	int countByExample(PensionPaymentdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	int deleteByExample(PensionPaymentdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	int insert(PensionPaymentdetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	int insertSelective(PensionPaymentdetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	List<PensionPaymentdetail> selectByExample(
			PensionPaymentdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	PensionPaymentdetail selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PensionPaymentdetail record,
			@Param("example") PensionPaymentdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	int updateByExample(@Param("record") PensionPaymentdetail record,
			@Param("example") PensionPaymentdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionPaymentdetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_paymentdetail
	 * @mbggenerated  Mon Sep 23 16:02:48 CST 2013
	 */
	int updateByPrimaryKey(PensionPaymentdetail record);
}