package persistence.financeManage;

import domain.financeManage.PensionFinancialpayment;
import domain.financeManage.PensionFinancialpaymentExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PensionFinancialpaymentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	int countByExample(PensionFinancialpaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	int deleteByExample(PensionFinancialpaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	int insert(PensionFinancialpayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	int insertSelective(PensionFinancialpayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	List<PensionFinancialpayment> selectByExample(
			PensionFinancialpaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	PensionFinancialpayment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	int updateByExampleSelective(
			@Param("record") PensionFinancialpayment record,
			@Param("example") PensionFinancialpaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	int updateByExample(@Param("record") PensionFinancialpayment record,
			@Param("example") PensionFinancialpaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	int updateByPrimaryKeySelective(PensionFinancialpayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pension_financialpayment
	 * @mbggenerated  Sun Nov 10 09:44:01 CST 2013
	 */
	int updateByPrimaryKey(PensionFinancialpayment record);

	List<PensionFinancialpayment> selectFinancialPayments(@Param("startDate")Date startDate, 
			@Param("endDate")Date endDate, 
			@Param("deptId")Long deptId,
			@Param("empId")Long empId);
}